[octopus]
wallet = cfx:aamjy3abae3j0ud8ys0npt38ggnunk5r4ps2pg8vcc
coin = CFX

[zil]
; for k1pool use the wallet from k1pool.com
wallet = KrYm3o9CtfQzhLjRPSUz2AEpTzNuQoUPLhf
pool1 = eu.etc.k1pool.com:1111

zilEpoch = 1 ; number of DAG epoch for caching

[verushash]
wallet = REoPcdGXthL5yeTCrJtrQv5xhYTknbFbec
coin = VRSC
rigName = speed_test
rigPassword=X
pool1=na.luckpool.net:3956
