# -*- coding: utf-8 -*-
import json
from pathlib import Path
out = Path(r"F:\backup\06-EVIDENCE\OCTOPUS-GAP-INVENTORY-2026-08-23")
out.mkdir(parents=True, exist_ok=True)
gaps = [
  {"id":"G01","rank":1,"severity":"P0","category":"5_board2","title":"Ziman Shopify accepts payments but payouts BLOCKED (AU bank/identity) + PayPal incomplete","claim":"Shop accepting payments / money infra GO / catalog for_sale","reality":"Payments UI accepting cards/Shop Pay BUT payouts blocked until bank/identity; Admin API scopes cannot manage payments; customers can pay while settlement incomplete","evidence":[r"F:\backup\06-EVIDENCE\BOARD2-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#C1",r"F:\backup\06-EVIDENCE\BOARD2-ZIMAN-MONEY-INFRA-2026-08-23\RESULT.json",r"F:\backup\06-EVIDENCE\OCTOPUS-CONTINUOUS-MISSION-2026-08-23\STATUS.json#PARTIAL_BLOCKED.ziman_bank_paypal_abn_noon"],"status":"OPEN","money_risk":True},
  {"id":"G02","rank":2,"severity":"P0","category":"5_board2","title":"Ziman gallery SKUs for_sale largely without product photos","claim":"Gallery products active including ZM-GALLERY-0007..0017","reality":"Only IMG_4109 uploaded (ZM-GALLERY-0016); marketing_notes still photos_binaries=NOT_YET on gallery SKUs","evidence":[r"F:\backup\06-EVIDENCE\BOARD2-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#C2",r"F:\backup\06-EVIDENCE\BOARD2-ZIMAN-GALLERY-PHOTOS-2026-08-23",r"F:\backup\06-EVIDENCE\BOARD2-ZIMAN-GALLERY-INGEST-2026-08-23"],"status":"OPEN"},
  {"id":"G03","rank":3,"severity":"P0","category":"8_freezes_flags_paper_live","title":"octopus-writer.lock EXPIRED while LIVE-TELEGRAM.flag still enabled","claim":"Single-writer lease governs live send exceptions","reality":"expires_at unix 1787435945 (renewed 07:44+10, ttl 900s); at scan remaining_s~-3012; forbidden_actions include live sendMessage + paid call; no send_exceptions","evidence":[r"F:\backup\_ops\state\locks\octopus-writer.lock",r"F:\backup\_ops\LIVE-TELEGRAM.flag",r"F:\backup\06-EVIDENCE\OCTOPUS-IOS-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#rank2"],"status":"OPEN"},
  {"id":"G04","rank":4,"severity":"P0","category":"1_telegram","title":"A18 Full Loop inbound still not CLOSED (outbound canary PASS) + stale BLOCKER labels","claim":"Some docs/BLOCKER.json still say A18/Full Loop BLOCKED as if canary never ran","reality":"Owner-chat canary mids 617/618 CONFIRMED via SenderBridge PASS; VERIFY does NOT claim durable_loop inbound CLOSED; BLOCKER.json status still BLOCKED","evidence":[r"F:\backup\06-EVIDENCE\OCTOPUS-A18-BLOCKER-2026-08-23\BLOCKER.json",r"F:\backup\06-EVIDENCE\OCTOPUS-A18-OWNER-CHAT-CANARY-2026-08-23\VERIFY.json",r"F:\backup\06-EVIDENCE\OCTOPUS-CONTINUOUS-MISSION-2026-08-23\STATUS.json#NEXT.A18_center_inbound_remember_correct",r"F:\backup\06-EVIDENCE\OCTOPUS-IOS-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#rank1,rank3",r"F:\backup\OCTOPUS\CURRENT-TRUTH.md"],"status":"PARTIAL"},
  {"id":"G05","rank":5,"severity":"P0","category":"1_telegram","title":"LIVE-TELEGRAM.flag enabled=true reads as live-send capable but unlock!=send","claim":"Flag enabled implies Telegram live capability","reality":"Flag note: Unlock only / does not by itself send; writer lock forbids live sendMessage by default; A18 exceptions rolled back","evidence":[r"F:\backup\_ops\LIVE-TELEGRAM.flag",r"F:\backup\_ops\state\locks\octopus-writer.lock",r"F:\backup\06-EVIDENCE\OCTOPUS-TELEGRAM-WIRE-FIX-2026-08-23\RESULT.json",r"F:\backup\06-EVIDENCE\OCTOPUS-IOS-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#rank2"],"status":"OPEN_DOC_DUAL_STATE"},
  {"id":"G06","rank":6,"severity":"P0","category":"4_wave0_mqtt_esp32","title":"WAVE0 physical Path H estop ABSENT; MQTT 1883 KEEP_CLOSED; soft!=physical","claim":"Soft-unlock authorized / WAVE0 progress","reality":"PACKAGE-STATUS hardware=BLOCKED_NEED_ESTOP mqtt=KEEP_CLOSED; soft-unlock AUTHORIZED only; physical PARTS-LIST LATER","evidence":[r"F:\backup\06-EVIDENCE\OCTOPUS-ORANGEPI-WAVE0-EXECUTE-2026-08-22\PACKAGE-STATUS.json",r"F:\backup\06-EVIDENCE\OCTOPUS-WAVE0-SOFT-ESTOP-UNLOCK-2026-08-23\RESULT.md",r"F:\backup\06-EVIDENCE\OCTOPUS-WAVE0-PHYSICAL-ESTOP-PARTS-2026-08-22\PARTS-LIST.md",r"F:\backup\07-HANDOFF\HANDOFF-OWNER-REVIEW-MERGE-2026-08-22.md"],"status":"DEFERRED_PHYSICAL"},
  {"id":"G07","rank":7,"severity":"P0","category":"10_multi_agent_handoffs","title":"Dirty worktree ~773 porcelain lines - multi-agent commit hygiene incomplete","claim":"Sparse commits / wave isolation","reality":"CONTINUOUS-DISCOVER cited ~692; scan count 773; evelab/doctor commits repeatedly skipped; WIRING.json skipped from continuous sparse commit; parallel Ios builder also wrote this folder","evidence":[r"F:\backup git porcelain count",r"F:\backup\06-EVIDENCE\OCTOPUS-EVELAB-DOCTOR-WIRE-2026-08-23\RESULT.json#commit",r"F:\backup\06-EVIDENCE\OCTOPUS-CONTINUOUS-MISSION-2026-08-23\STATUS.json#sparse_commit",r"F:\backup\06-EVIDENCE\OCTOPUS-GAP-INVENTORY-2026-08-23\_build_inventory.py"],"status":"OPEN"},
  {"id":"G08","rank":8,"severity":"HIGH","category":"1_telegram","title":"Dual/triple Telegram outbox surfaces (durable loop + event-bridge + urgent)","claim":"Single organism SoT outbox","reality":"Durable loop/outbox (21 items C18/DL2/DR1) PLUS event-bridge-outbox.jsonl PLUS urgent-outbox.jsonl; canary sqlite remains non-SoT","evidence":[r"F:\backup\_ops\state\telegram\loop\outbox",r"F:\backup\_ops\state\telegram\event-bridge-outbox.jsonl",r"F:\backup\_ops\state\telegram\urgent-outbox.jsonl",r"F:\backup\06-EVIDENCE\OCTOPUS-TELEGRAM-WIRE-FIX-2026-08-23\RESULT.json#C05",r"F:\backup\06-EVIDENCE\OCTOPUS-OUTBOX-DEAD-LETTER-2026-08-23\RESULT.json"],"status":"OPEN"},
  {"id":"G09","rank":9,"severity":"HIGH","category":"1_telegram","title":"SenderBridge center attach default-OFF; poll-loop not wired to owner_gated_sender_bridge_run_once","claim":"Center has SenderBridge path after wire-fix","reality":"center_sender_bridge.py + center.owner_gated_sender_bridge_run_once refuse without exception; NEXT optional wire poll-loop still open","evidence":[r"F:\backup\_ops\telegram_center\center_sender_bridge.py",r"F:\backup\_ops\telegram_center\center.py",r"F:\backup\06-EVIDENCE\OCTOPUS-TELEGRAM-WIRE-FIX-2026-08-23\RESULT.json",r"F:\backup\_ops\telegram_center\live_telegram_gate.py"],"status":"PARTIAL_WIRED_DEFAULT_OFF"},
  {"id":"G10","rank":10,"severity":"HIGH","category":"1_telegram","title":"MiniApp public URL / env / docs mismatch vs live localhost + cloudflared state","claim":"Reconcile: public URL NOT_PUBLISHED; OCTOPUS_MINIAPP_URL unset; Telegram UI CONFIG_NEEDED","reality":"miniapp_gateway PID 12220 LIVE on 127.0.0.1:8774; miniapp-url.json has https://app.master-painting.com (kind=named); cloudflared PID 8512 ALIVE; env keys unset","evidence":[r"F:\backup\06-EVIDENCE\OCTOPUS-MINIAPP-DOC-RECONCILE-2026-08-23\RESULT.json",r"F:\backup\_ops\state\telegram\miniapp-url.json",r"F:\backup\_ops\telegram_center\miniapp_gateway.py",r"F:\backup\06-EVIDENCE\OCTOPUS-IOS-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#rank9"],"status":"OPEN_CONTRADICTION"},
  {"id":"G11","rank":11,"severity":"HIGH","category":"5_board2","title":"Board2 OFN wire/keep-gates-open flags ON while auto_* paths CLOSED; studio manual-only","claim":"OFN_WIRE_* / KEEP_GATES_OPEN suggest live outbound organism","reality":"OFN_EXTRA_CLOSED_GATES lists auto_post,auto_dm,auto_email,live_sms,live_dm,...; studio publishes manual_completed only","evidence":[r"F:\backup\06-EVIDENCE\BOARD2-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#C3",r"F:\backup\06-EVIDENCE\BOARD2-STUDIO-BATCH-QUEUE-2026-08-23"],"status":"OPEN"},
  {"id":"G12","rank":12,"severity":"HIGH","category":"5_board2","title":"Studio captions HOLD shot-0003..0022 + draft status not flipped after publish","claim":"Library 22/22 ready; unlock/wire open; batch GO","reality":"Only 0001/0002 published; 0003-0022 HOLD empty captions; drafts remain status=draft after publish","evidence":[r"F:\backup\06-EVIDENCE\BOARD2-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#C4",r"F:\backup\06-EVIDENCE\BOARD2-STUDIO-BATCH-QUEUE-2026-08-23",r"F:\backup\06-EVIDENCE\OCTOPUS-CONTINUOUS-MISSION-2026-08-23\STATUS.json#PARTIAL_BLOCKED.studio_captions"],"status":"OPEN"},
  {"id":"G13","rank":13,"severity":"HIGH","category":"5_board2","title":"Studio duplicate shot-0002 Telegram posts + Etsy HELD vs listing language","claim":"One shot-0002 publish; Etsy listing path live-ish","reality":"Two manual_completed outbox items (unlock + batch); Etsy shop pending-review / adapter not live","evidence":[r"F:\backup\06-EVIDENCE\BOARD2-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#C5,C6",r"F:\backup\06-EVIDENCE\BOARD2-STUDIO-DUP-0002-NOTE-2026-08-23",r"F:\backup\06-EVIDENCE\BOARD2-ZIMAN-ETSY-LISTING-2026-08-22"],"status":"OPEN"},
  {"id":"G14","rank":14,"severity":"HIGH","category":"6_wiring_mismatches","title":"WIRING.json studio_wire=false vs Board2 Studio Telegram publish (OOB path)","claim":"studio_wire=false means no Studio Telegram","reality":"Board2 OOB publish true; cartographer does not own Studio; policy note added but dashboards can misread flag","evidence":[r"F:\backup\_ops\organs\WIRING.json#hooks.studio_board2_oob",r"F:\backup\06-EVIDENCE\BOARD2-STUDIO-PUBLISH-DRAIN-2026-08-22",r"F:\backup\06-EVIDENCE\OCTOPUS-IOS-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#rank4"],"status":"DOCUMENTED_MISMATCH"},
  {"id":"G15","rank":15,"severity":"HIGH","category":"6_wiring_mismatches","title":"WIRING money wires false NOW vs iOS scan (08:20) that saw mining/crypto/accounting true","claim":"iOS CONTRADICTIONS rank5: mining/crypto/accounting true vs money-off","reality":"Current WIRING.json post-08:25 reconcile has mining/crypto/accounting/studio false + money_wires_policy; prior contradiction evidence remains as drift class","evidence":[r"F:\backup\_ops\organs\WIRING.json",r"F:\backup\06-EVIDENCE\OCTOPUS-IOS-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#rank5"],"status":"RECONCILED_FLAGS_STALE_EVIDENCE_REMAINS"},
  {"id":"G16","rank":16,"severity":"HIGH","category":"3_epistemics","title":"Epistemics wire ON_ADVISORY_LIVE but topology pack still lists OFF/A18-BLOCKED gaps; channel/identifiability non-authoritative","claim":"Topology RESULT: OCTOPUS_WIRE_EPISTEMICS left OFF; A18 canary still BLOCKED","reality":"WIRE-ON PASS ON_ADVISORY; STATUS ON_ADVISORY_LIVE organism 29020; levels/self_reference/method authoritative; ident/channel below MIN_SAMPLES; algebraic_connectivity=0","evidence":[r"F:\backup\06-EVIDENCE\OCTOPUS-EPISTEMICS-TOPOLOGY-2026-08-23\RESULT.json",r"F:\backup\06-EVIDENCE\OCTOPUS-EPISTEMICS-WIRE-ON-2026-08-23\RESULT.json",r"F:\backup\06-EVIDENCE\OCTOPUS-CONTINUOUS-MISSION-2026-08-23\STATUS.json",r"F:\backup\06-EVIDENCE\OCTOPUS-IOS-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#rank6",r"F:\backup\_ops\epistemics\readers.py"],"status":"PARTIAL"},
  {"id":"G17","rank":17,"severity":"HIGH","category":"8_freezes_flags_paper_live","title":"ACTIVATION-* flags (2026-07-22 resurrection) claim all paid gates ON vs lock forbids paid + PAPER profile","claim":"ACTIVATION-GO-LIVE / CORTEX-PAID / SELF-IMPROVE-AUTO armed","reality":"Many *.flag files say all paid gates ON; writer lock forbids paid call; default OCTOPUS_PROFILE paper-full; FREEZE released 2026-08-19 but flag sprawl uncleared","evidence":[r"F:\backup\_ops\ACTIVATION-GO-LIVE.flag",r"F:\backup\_ops\ACTIVATION-CORTEX-PAID.flag",r"F:\backup\_ops\ACTIVATION-SELF-IMPROVE-AUTO.flag",r"F:\backup\_ops\state\locks\octopus-writer.lock",r"F:\backup\_ops\wiring.py",r"F:\backup\_ops\budget\FREEZE-RELEASE-RECEIPT.json",r"F:\backup\_ops\state\LIVE-ENABLED.flag"],"status":"OPEN_FLAG_SPRAWL"},
  {"id":"G18","rank":18,"severity":"HIGH","category":"2_doctor_evelab","title":"evelab/lab_bridge/self_upgrade_lab = propose-only wire; not a continuous promote schedule","claim":"Evolutionary lab <-> doctor is a real path","reality":"lab_bridge propose_lab_experiment_ticket -> durable outbox live_send=false; merge still human; no Windows cron under _ops for evelab promote; uniqueness IS on Pacemaker","evidence":[r"F:\backup\_ops\doctor\lab_bridge.py",r"F:\backup\06-EVIDENCE\OCTOPUS-EVELAB-DOCTOR-WIRE-2026-08-23\RESULT.json",r"F:\backup\_ops\self_upgrade_lab",r"F:\backup\06-EVIDENCE\OCTOPUS-DOCTOR-UNIQUENESS-HEARTBEAT-2026-08-23\RESULT.json#schedule_discovery",r"F:\backup\06-EVIDENCE\SELF-UPGRADE-LAB-CYCLE-2026-08-21"],"status":"WIRED_PROPOSE_ONLY"},
  {"id":"G19","rank":19,"severity":"MED","category":"2_doctor_evelab","title":"Doctor uniqueness heartbeat on disk; continuous soak depends on organism process epoch","claim":"poller_uniqueness continuous","reality":"wiring.doctor_uniqueness_beat + organism hook PASS; receipts under state/doctor; fail-closed RO; continuous mission cites uniqueness_natural_soak PASS","evidence":[r"F:\backup\06-EVIDENCE\OCTOPUS-DOCTOR-UNIQUENESS-HEARTBEAT-2026-08-23\RESULT.json",r"F:\backup\_ops\doctor\uniqueness_heartbeat.py",r"F:\backup\_ops\state\doctor\poller-uniqueness-latest.json",r"F:\backup\06-EVIDENCE\OCTOPUS-CONTINUOUS-MISSION-2026-08-23\STATUS.json#uniqueness_natural_soak"],"status":"MOSTLY_CLOSED_MONITOR"},
  {"id":"G20","rank":20,"severity":"MED","category":"5_board2","title":"GST ABN empty + ZM-GALLERY-0016 note drift after photo upload","claim":"GST OK / photo upload PASS clears NOT_YET","reality":"AU GST collecting but ABN empty (deferred noon vault); 0016 marketing_notes still photos_binaries=NOT_YET after IMG_4109 PASS","evidence":[r"F:\backup\06-EVIDENCE\BOARD2-CONTRADICTION-SCAN-2026-08-23\CONTRADICTIONS.json#C7,C9"],"status":"OPEN"},
  {"id":"G21","rank":21,"severity":"MED","category":"10_multi_agent_handoffs","title":"Multi-agent handoffs incomplete / stale open checkboxes","claim":"NEXT-AGENT / WAVE-B / merge handoffs current","reality":"07-HANDOFF/NEXT-AGENT-HANDOFF.md dated 2026-08-15 with open NEW-1/NEW-2; WAVE-B retains uncommitted-wave-b.patch; merge pointer exists; live locks still WAVE0 KEEP_LOCKED / MQTT CLOSED","evidence":[r"F:\backup\07-HANDOFF\NEXT-AGENT-HANDOFF.md",r"F:\backup\06-EVIDENCE\OCTOPUS-WAVE-B-HANDOFF-2026-08-21\uncommitted-wave-b.patch",r"F:\backup\06-EVIDENCE\OCTOPUS-WAVE-B-HANDOFF-2026-08-21\HANDOFF.md",r"F:\backup\07-HANDOFF\HANDOFF-OWNER-REVIEW-MERGE-2026-08-22.md"],"status":"STALE_PARTIAL"},
  {"id":"G22","rank":22,"severity":"MED","category":"7_orphan_todo","title":"Orphan / legacy scripts under _ops/scripts + bridge shells","claim":"Scripts are active organism paths","reality":"16 files in _ops/scripts including tg_bridge_loop.sh, tg_bridge_once.py, unlock_self_progress.py — parallel to telegram_center durable loop","evidence":[r"F:\backup\_ops\scripts\tg_bridge_loop.sh",r"F:\backup\_ops\scripts\tg_bridge_once.py",r"F:\backup\_ops\scripts\unlock_self_progress.py",r"F:\backup\_ops\scripts\golden_trace_miniapp.py",r"F:\backup\_ops\scripts"],"status":"OPEN"},
  {"id":"G23","rank":23,"severity":"MED","category":"7_orphan_todo","title":"TODO/FIXME/XXX/DEFERRED markers in _ops (59 clean hits; sample file)","claim":"metrics.py header still says DATA ADAPTERS are TODO","reality":"readers.py enriched 2026-08-23; metrics.py still contains readers TODO strings; contracts.py TODO(GLM) calibrate; deploy-to-live.ps1 DEFERRED watchdog registration","evidence":[r"F:\backup\06-EVIDENCE\OCTOPUS-GAP-INVENTORY-2026-08-23\TODO-SAMPLE-TOP80.txt",r"F:\backup\_ops\epistemics\metrics.py",r"F:\backup\_ops\epistemics\contracts.py",r"F:\backup\_ops\deploy\deploy-to-live.ps1"],"status":"OPEN","todo_sample_file":r"F:\backup\06-EVIDENCE\OCTOPUS-GAP-INVENTORY-2026-08-23\TODO-SAMPLE-TOP80.txt","todo_clean_hit_count":59},
  {"id":"G24","rank":24,"severity":"MED","category":"9_tests_docs","title":"Tests sprawl (845 test_*.py); some not named in run_all; Aug-16 UNWIRED docs may be stale","claim":"Every test is in continuous runner; UNWIRED reports still current","reality":"sample 200 tests => 2 not named in run_all.py; UNWIRED-effect-zero/http8765/4d-consolidation dated 2026-08-16 without supersede stamp","evidence":[r"F:\backup\_ops\tests",r"F:\backup\_ops\tests\run_all.py",r"F:\backup\_ops\tests\test_close_c025_family_key_20260816.py",r"F:\backup\_ops\tests\test_close_experiments_retired_20260816.py",r"F:\backup\06-EVIDENCE\UNWIRED-effect-zero-2026-08-16.md",r"F:\backup\06-EVIDENCE\UNWIRED-http8765-2026-08-16.md"],"status":"OPEN"},
  {"id":"G25","rank":25,"severity":"MED","category":"3_epistemics","title":"Topology Laplacian algebraic_connectivity=0 / spectral_gap=0 (disconnected components)","claim":"levels metric authoritative sample>=8","reality":"Authoritative spectrum exists but algebraic_connectivity -0.0 and spectral_gap 0.0 — organ islands","evidence":[r"F:\backup\06-EVIDENCE\OCTOPUS-EPISTEMICS-TOPOLOGY-2026-08-23\RESULT.json#levels_metric",r"F:\backup\_ops\epistemics\readers.py"],"status":"OPEN_MATH_SIGNAL"},
]
doc = {
  "schema": "octopus-gap-inventory/1",
  "task": "OCTOPUS-GAP-INVENTORY-2026-08-23",
  "producer": "grok-executor-subagent",
  "stamp_local": "2026-08-23T08:55:00+10:00",
  "timezone": "Australia/Sydney",
  "constraints_honored": {"no_live_send": True, "no_secrets": True, "no_invent": True, "evidence_backed_only": True},
  "method": "Read-only scan of F:\\backup evidence packs + _ops state/flags/WIRING + recent RESULT/CONTRADICTIONS; rank by severity; cite paths.",
  "live_snapshot_readonly": {
    "writer_lock_expired": True,
    "writer_lock_path": r"F:\backup\_ops\state\locks\octopus-writer.lock",
    "writer_lock_expires_at_unix": 1787435945.727212,
    "writer_lock_renewed_at_local": "2026-08-23T07:44:12.327+10:00",
    "writer_lock_remaining_s_at_scan": -3012.3,
    "dirty_worktree_porcelain_count": 773,
    "miniapp_gateway_pid": 12220,
    "cloudflared_pid_8512_alive": True,
    "miniapp_url_state_file": r"F:\backup\_ops\state\telegram\miniapp-url.json"
  },
  "parallel_note": "Ios agent also wrote _build_inventory.py / IOS-GAPS.json into this folder; preserved separately. This GAPS.json is the owner-requested 10-category ranked inventory.",
  "category_index": ["1_telegram","2_doctor_evelab","3_epistemics","4_wave0_mqtt_esp32","5_board2","6_wiring_mismatches","7_orphan_todo","8_freezes_flags_paper_live","9_tests_docs","10_multi_agent_handoffs"],
  "gaps": gaps,
  "top25_ids": [g["id"] for g in gaps],
  "todo_sample": {
    "clean_hits": 59,
    "requested_top": 80,
    "file": r"F:\backup\06-EVIDENCE\OCTOPUS-GAP-INVENTORY-2026-08-23\TODO-SAMPLE-TOP80.txt",
    "note": "Strict TODO|FIXME|XXX|DEFERRED/BLOCKED-until filter; enum/assert noise excluded. Fewer than 80 clean hits."
  }
}
gaps_path = out / "GAPS.json"
tmp = out / "GAPS.json.tmp-grok"
tmp.write_text(json.dumps(doc, ensure_ascii=False, indent=2), encoding="utf-8")
tmp.replace(gaps_path)
v = json.loads(gaps_path.read_text(encoding="utf-8"))
assert v["producer"] == "grok-executor-subagent" and len(v["gaps"]) == 25
print("VERIFY_OK", gaps_path, "bytes", gaps_path.stat().st_size)
for p in sorted(out.iterdir()):
    print(f"{p.name}\t{p.stat().st_size}")
