# -*- coding: utf-8 -*-
"""12 AGI families (execution/SLA) + 24 discovery loops (seam checklist).

Families are the unit you close. Discovery loops are the unit you hunt.
Neither is a claim of biological AGI / consciousness.
"""
from __future__ import annotations

# Claude 12-family execution units.
FAMILIES: tuple[dict, ...] = (
    {"family_id": "AGI-01", "name": "perception", "sla_s": 259200,
     "problem": "inbound telegram/miniapp events reach one authenticated gateway",
     "seeds": ["S-T01", "D23", "D14"]},
    {"family_id": "AGI-02", "name": "attention", "sla_s": 86400,
     "problem": "salience without spam; probe-invalid must not flood owner",
     "seeds": ["D01", "LOOP-TELEGRAM-PROBE-INVALID", "S-T03"]},
    {"family_id": "AGI-03", "name": "memory", "sla_s": 259200,
     "problem": "read-only wave: mutation==0; gate F3 + two-phase admission",
     "seeds": ["D05", "D06", "MEMORY-GATE-REPAIR"]},
    {"family_id": "AGI-04", "name": "learning", "sla_s": 259200,
     "problem": "calibration-latest → improve; receipt EMA not constant 0.4",
     "seeds": ["S-A03", "S-A01", "D07", "D08"]},
    {"family_id": "AGI-05", "name": "decision", "sla_s": 259200,
     "problem": "one Decision Ledger; silence≠approval; pending digest to owner",
     "seeds": ["LOOP-APPROVAL-QUEUE", "D19"]},
    {"family_id": "AGI-06", "name": "owner_surface", "sla_s": 259200,
     "problem": "telegram + miniapp are one façade; L6 OWNER_VISIBLE required for CLOSED",
     "seeds": ["D10", "D11", "S-T01"]},
    {"family_id": "AGI-07", "name": "effector", "sla_s": 259200,
     "problem": "outbox + update_id idempotency; business_retry ≠ delivery_retry",
     "seeds": ["D12", "D24", "S-T02"]},
    {"family_id": "AGI-08", "name": "sleep", "sla_s": 1209600,
     "problem": "F-AUTO-ALERT files → aggregate counter; no new file per repeat",
     "seeds": ["S-D07", "D22"]},
    {"family_id": "AGI-09", "name": "immune", "sla_s": 259200,
     "problem": "doctor one-open-mission + timeout + quarantine; no production deadlock",
     "seeds": ["S-D01", "D17", "D18"]},
    {"family_id": "AGI-10", "name": "identity", "sla_s": 259200,
     "problem": "self_knowledge / self_insight consumed; no fake-green awareness",
     "seeds": ["S-A02", "S-A08", "S-D04", "D09"]},
    {"family_id": "AGI-11", "name": "reality", "sla_s": 259200,
     "problem": "contradictions preserved; NO_BASELINE is a truth state not a fake compare",
     "seeds": ["S-B05", "D04", "D20"]},
    {"family_id": "AGI-12", "name": "survival", "sla_s": 86400,
     "problem": "429 retry_after blocks the whole bot; digest is a send precondition; no paid calls",
     "seeds": ["S-B01", "S-T03", "D13"]},
)

# GPT-5.6 Sol 24-loop discovery checklist (hunt seams, do not SLA-close at this grain).
DISCOVERY: tuple[dict, ...] = (
    {"loop_id": "D01", "title": "attention / salience", "family_id": "AGI-02"},
    {"loop_id": "D02", "title": "curiosity / uncertainty reduction", "family_id": "AGI-04"},
    {"loop_id": "D03", "title": "pain / nociception", "family_id": "AGI-09"},
    {"loop_id": "D04", "title": "contradiction / reality reconciliation", "family_id": "AGI-11"},
    {"loop_id": "D05", "title": "memory read (scoped, receipted)", "family_id": "AGI-03"},
    {"loop_id": "D06", "title": "memory write-guard (wave mutation==0)", "family_id": "AGI-03"},
    {"loop_id": "D07", "title": "calibration-latest consumed by improve", "family_id": "AGI-04"},
    {"loop_id": "D08", "title": "confidence EMA receipt-backed", "family_id": "AGI-04"},
    {"loop_id": "D09", "title": "self_insight explicit shadow cycle", "family_id": "AGI-10"},
    {"loop_id": "D10", "title": "owner telegram visibility (L6)", "family_id": "AGI-06"},
    {"loop_id": "D11", "title": "miniapp unified façade", "family_id": "AGI-06"},
    {"loop_id": "D12", "title": "outbox + update_id idempotency", "family_id": "AGI-07"},
    {"loop_id": "D13", "title": "digest/coalesce (429 retry_after whole-bot)", "family_id": "AGI-12"},
    {"loop_id": "D14", "title": "webhook+polling dual ingest", "family_id": "AGI-01"},
    {"loop_id": "D15", "title": "bot ingesting its own replies", "family_id": "AGI-01"},
    {"loop_id": "D16", "title": "scanner rediscovering its own findings", "family_id": "AGI-08"},
    {"loop_id": "D17", "title": "green heartbeat / dead worker", "family_id": "AGI-09"},
    {"loop_id": "D18", "title": "doctor mission deadlock", "family_id": "AGI-09"},
    {"loop_id": "D19", "title": "approval queue owner digest", "family_id": "AGI-05"},
    {"loop_id": "D20", "title": "brain_core NO_BASELINE truth state", "family_id": "AGI-11"},
    {"loop_id": "D21", "title": "orphan supervision observe-only", "family_id": "AGI-12"},
    {"loop_id": "D22", "title": "sleep: F-AUTO-ALERT aggregation", "family_id": "AGI-08"},
    {"loop_id": "D23", "title": "initData HMAC-SHA256 WebAppData", "family_id": "AGI-01"},
    {"loop_id": "D24", "title": "restart-no-resend", "family_id": "AGI-07"},
)

# Gemini byte sprint — file-level first tasks. Pass 3 LIVE only after T-01..T-24.
BYTE_SPRINT: tuple[dict, ...] = (
    {"byte": 1, "file": "_ops/telegram_center/miniapp_gateway.py",
     "task": "confirm unified façade (initData before any data byte)"},
    {"byte": 2, "file": "_ops/telegram_center/miniapp_gateway.py:validate_init_data",
     "task": "HMAC(WebAppData, token) then sign data-check-string; T-05 tamper reject"},
    {"byte": 3, "file": "_ops/conversation_hub / Decision Ledger",
     "task": "telegram and miniapp share one ledger — no parallel approval brains"},
    {"byte": 4, "file": "_ops/loops/telegram_organ.py",
     "task": "outbox + update_id idempotency; T-08 restart-no-resend"},
    {"byte": 5, "file": "BotFather menu button → /miniapp",
     "task": "LIVE only — four tabs; not this order"},
    {"byte": 6, "file": "brain_core parity",
     "task": "keep NO_BASELINE as truth; do not invent a baseline"},
    {"byte": 7, "file": "_ops/cortex/improve.py",
     "task": "SHADOW: calibration-latest → gather_signals / generate_proposals"},
    {"byte": 8, "file": "_ops/doctor/self_knowledge.py",
     "task": "SHADOW: constant 0.4 → receipt EMA"},
    {"byte": 9, "file": "OCTOPUS-DOCTOR/doctor/daemon.py",
     "task": "SHADOW: open-mission timeout + quarantine"},
    {"byte": 10, "file": "_ops/loops/telegram_organ.py:enqueue_digest",
     "task": "SHADOW: 42 seams = 1 digest; T-22"},
    {"byte": 11, "file": "_ops/telegram_center/center.py",
     "task": "HUNT T-21: webhook+polling dual ingest (read-only; WORKLOCK)"},
    {"byte": 12, "file": "ingest own replies",
     "task": "HUNT: bot must not ingest from.id==bot"},
    {"byte": 13, "file": "doctor-pulse / heartbeat",
     "task": "HUNT: green heartbeat with dead worker"},
)
