"""VaultScanner — READ-ONLY Obsidian vault analysis (Phase 2, spec §13).

Parses markdown notes (frontmatter, [[wikilinks]], #tags), builds a link graph,
finds orphans, and infers cross-folder "hidden channels" with evidence and a
confidence score. It NEVER writes to the vault. Restricted folders (People /
Crypto-eToro / Telegram) are excluded unless the owner opts in per the data-safety
spine. Stdlib only; the resulting channel map is written into the vault only later,
as a B6 ActionProposal the owner approves — not by this scanner.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

# Excluded unless include_restricted=True (build plan data-safety spine):
DEFAULT_RESTRICTED: tuple[str, ...] = (
    "09 - People",
    "10 - Telegram processing",
    "03 - Projects/Crypto - etoro",
)

_WIKILINK = re.compile(r"\[\[([^\]|#]+)")
_TAG = re.compile(r"(?:^|\s)#([A-Za-z0-9_\-/]+)")
_CRITICAL_HINTS = ("People", "Crypto", "Telegram", "Accounting")


@dataclass(frozen=True)
class Note:
    path: str                       # vault-relative, forward slashes
    folder: str                     # top-level folder
    title: str                      # filename stem
    frontmatter: dict
    wikilinks: tuple[str, ...]
    tags: tuple[str, ...]


@dataclass(frozen=True)
class Channel:
    channel_id: str
    type: str                       # "inferred"
    from_folder: str
    to_folder: str
    evidence: tuple[str, ...]
    confidence: float               # 0.0–1.0
    risk_level: str                 # low | medium | high | critical
    recommended_action: str


@dataclass(frozen=True)
class ScanResult:
    notes: tuple[Note, ...]
    channels: tuple[Channel, ...]
    orphans: tuple[str, ...]        # titles with no in/out links
    excluded_folders: tuple[str, ...]

    def to_channel_map_md(self) -> str:
        lines = [
            "# Channel Map (generated by the read-only vault scanner)",
            "",
            f"- notes scanned: {len(self.notes)}",
            f"- channels inferred: {len(self.channels)}",
            f"- orphans: {len(self.orphans)}",
            f"- excluded folders: {', '.join(self.excluded_folders) or '(none)'}",
            "",
            "## Inferred channels",
        ]
        for c in self.channels:
            lines += [
                f"- **{c.channel_id}** ({c.risk_level}, conf {c.confidence})"
                f" `{c.from_folder}` → `{c.to_folder}`",
                f"  - evidence: {', '.join(c.evidence)}",
                f"  - recommended: {c.recommended_action}",
            ]
        lines += ["", "## Orphans", *(f"- {t}" for t in self.orphans)]
        return "\n".join(lines) + "\n"


def _top_folder(rel: Path) -> str:
    parts = rel.parts
    return parts[0] if len(parts) > 1 else "(root)"


def _is_excluded(rel_posix: str, excluded: Sequence[str]) -> bool:
    return any(rel_posix == e or rel_posix.startswith(e + "/") for e in excluded)


def _parse_frontmatter(text: str) -> tuple[dict, str]:
    """Minimal frontmatter reader (flat top-level scalars). Returns (fm, body)."""
    if not text.startswith("---"):
        return {}, text
    lines = text.splitlines()
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return {}, text
    fm: dict = {}
    for line in lines[1:end]:
        if line[:1].isspace() or ":" not in line:
            continue  # skip nested/indented lines in this minimal reader
        key, _, value = line.partition(":")
        fm[key.strip()] = value.strip()
    return fm, "\n".join(lines[end + 1:])


def _risk_from_paths(paths) -> str:
    """Risk of a channel judged from the REAL note paths involved. A note's top-level
    folder collapses subfolders (e.g. '03 - Projects/Crypto - etoro' -> '03 - Projects'),
    so risk must be read from full paths, not the collapsed folder names, or a crypto
    channel would be mislabeled 'medium' instead of 'critical'."""
    blob = " ".join(paths)
    if "Crypto" in blob or "Telegram" in blob:
        return "critical"
    if any(h in blob for h in _CRITICAL_HINTS):
        return "high"
    return "medium"


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


class VaultScanner:
    """Read-only. Point it at a vault root; call `scan()`. Writes nothing."""

    def __init__(
        self,
        root: str | Path,
        *,
        exclude_folders: Sequence[str] = DEFAULT_RESTRICTED,
        include_restricted: bool = False,
        channel_threshold: int = 3,
    ) -> None:
        self._root = Path(root)
        self._excluded = tuple(() if include_restricted else exclude_folders)
        self._threshold = max(1, channel_threshold)

    def scan(self) -> ScanResult:
        notes = self._read_notes()
        title_index = {n.title: n for n in notes}

        outdeg: dict[str, int] = {n.title: 0 for n in notes}
        indeg: dict[str, int] = {n.title: 0 for n in notes}
        pair_evidence: dict[tuple[str, str], set[str]] = {}
        pair_paths: dict[tuple[str, str], set[str]] = {}

        for note in notes:
            for raw_link in note.wikilinks:
                target = title_index.get(raw_link.strip())
                if target is None:
                    continue  # unresolved (e.g., points into an excluded folder)
                outdeg[note.title] += 1
                indeg[target.title] += 1
                if target.folder != note.folder:
                    key = (note.folder, target.folder)
                    pair_evidence.setdefault(key, set()).add(note.title)
                    pair_paths.setdefault(key, set()).update((note.path, target.path))

        channels = tuple(
            Channel(
                channel_id=f"ch_{_slug(f)}__{_slug(t)}",
                type="inferred",
                from_folder=f,
                to_folder=t,
                evidence=tuple(sorted(ev)),
                confidence=round(min(1.0, len(ev) / self._threshold), 2),
                risk_level=_risk_from_paths(pair_paths[(f, t)]),
                recommended_action="formalize handoff channel",
            )
            for (f, t), ev in sorted(pair_evidence.items())
        )
        orphans = tuple(
            sorted(n.title for n in notes if outdeg[n.title] == 0 and indeg[n.title] == 0)
        )
        return ScanResult(
            notes=notes, channels=channels, orphans=orphans, excluded_folders=self._excluded
        )

    def _read_notes(self) -> tuple[Note, ...]:
        out: list[Note] = []
        root_real = self._root.resolve()
        for path in sorted(self._root.rglob("*.md")):
            # Exclusion must reflect the REAL location: resolve symlinks/junctions so a
            # link inside an included folder that targets a restricted one is still
            # excluded, and a link escaping the vault is skipped (fail-closed spine).
            try:
                rel = path.resolve().relative_to(root_real)
            except (ValueError, OSError):
                continue  # resolves outside the vault, or unresolvable -> skip
            rel_posix = rel.as_posix()
            if _is_excluded(rel_posix, self._excluded):
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            fm, body = _parse_frontmatter(text)
            out.append(
                Note(
                    path=rel_posix,
                    folder=_top_folder(rel),
                    title=rel.stem,
                    frontmatter=fm,
                    wikilinks=tuple(m.group(1).strip() for m in _WIKILINK.finditer(body)),
                    tags=tuple(sorted({m.group(1) for m in _TAG.finditer(body)})),
                )
            )
        return tuple(out)
