#!/usr/bin/env python
"""
AGI Investment Landscape Report - August 2026
Generates a comprehensive PDF covering 25+ investment topics across 8 categories.
"""

import os
import sys

# ── PDF Skill Path ──
PDF_SKILL_DIR = r"C:\Users\Armin\.zcode\cli\plugins\cache\zcode-plugins-official\document-skills\0.1.0\skills\pdf"
_scripts = os.path.join(PDF_SKILL_DIR, "scripts")
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, CondPageBreak, Image, PageBreak
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
import hashlib

# ━━ Color Palette (auto-generated by palette.cascade) ━━
from reportlab.lib import colors as _c

PAGE_BG      = _c.HexColor('#f1f1f0')
SECTION_BG   = _c.HexColor('#f0efee')
CARD_BG      = _c.HexColor('#eae8e4')
TABLE_STRIPE = _c.HexColor('#ececea')

HEADER_FILL  = _c.HexColor('#766c50')
COVER_BLOCK = _c.HexColor('#635c46')

BORDER = _c.HexColor('#c8c0a8')
ICON   = _c.HexColor('#958555')

ACCENT   = _c.HexColor('#1f7693')
ACCENT_2 = _c.HexColor('#54c954')

TEXT_PRIMARY = _c.HexColor('#252422')
TEXT_MUTED   = _c.HexColor('#7e7c74')

SEM_SUCCESS = _c.HexColor('#4a9161')
SEM_WARNING = _c.HexColor('#a38750')
SEM_ERROR   = _c.HexColor('#984d46')
SEM_INFO    = _c.HexColor('#4d6884')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ── Output Paths ──
OUTPUT_DIR = r"F:\backup"
BODY_PDF   = os.path.join(OUTPUT_DIR, "agi_body.pdf")
FINAL_PDF  = os.path.join(OUTPUT_DIR, "AGI_Investment_Landscape_August_2026.pdf")

# ── Font Registration (Windows paths) ──
FONT_DIR = r"C:\Windows\Fonts"
pdfmetrics.registerFont(TTFont('Times New Roman', os.path.join(FONT_DIR, 'times.ttf')))
pdfmetrics.registerFont(TTFont('Times New Roman Bold', os.path.join(FONT_DIR, 'timesbd.ttf')))
pdfmetrics.registerFont(TTFont('Calibri', os.path.join(FONT_DIR, 'calibri.ttf')))
pdfmetrics.registerFont(TTFont('Calibri Bold', os.path.join(FONT_DIR, 'calibrib.ttf')))

registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman Bold')
registerFontFamily('Calibri', normal='Calibri', bold='Calibri Bold')

# ── Page Dimensions ──
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.85 * inch
BOTTOM_MARGIN = 0.85 * inch
CONTENT_W = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN
H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

# ── Styles ──
styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    name='ReportTitle', fontName='Times New Roman', fontSize=28,
    leading=34, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceAfter=4
)

h1_style = ParagraphStyle(
    name='H1Style', fontName='Times New Roman', fontSize=20,
    leading=26, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceBefore=18, spaceAfter=10
)

h2_style = ParagraphStyle(
    name='H2Style', fontName='Times New Roman', fontSize=14,
    leading=19, alignment=TA_LEFT, textColor=ACCENT,
    spaceBefore=14, spaceAfter=6
)

h3_style = ParagraphStyle(
    name='H3Style', fontName='Times New Roman', fontSize=12,
    leading=16, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceBefore=10, spaceAfter=4
)

body_style = ParagraphStyle(
    name='BodyStyle', fontName='Times New Roman', fontSize=10.5,
    leading=17, alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
    spaceBefore=0, spaceAfter=6
)

bullet_style = ParagraphStyle(
    name='BulletStyle', fontName='Times New Roman', fontSize=10.5,
    leading=17, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    leftIndent=18, bulletIndent=6, spaceBefore=2, spaceAfter=2,
    bulletFontName='Times New Roman', bulletFontSize=10.5
)

caption_style = ParagraphStyle(
    name='CaptionStyle', fontName='Times New Roman', fontSize=9,
    leading=13, alignment=TA_CENTER, textColor=TEXT_MUTED,
    spaceBefore=3, spaceAfter=6
)

toc_h1 = ParagraphStyle(name='TOCH1', fontSize=13, leftIndent=20,
                         fontName='Times New Roman', leading=22, textColor=TEXT_PRIMARY)
toc_h2 = ParagraphStyle(name='TOCH2', fontSize=11, leftIndent=40,
                         fontName='Times New Roman', leading=18, textColor=TEXT_MUTED)

header_cell_style = ParagraphStyle(
    name='HeaderCell', fontName='Times New Roman', fontSize=10,
    leading=14, textColor=colors.white, alignment=TA_CENTER
)

cell_style = ParagraphStyle(
    name='CellStyle', fontName='Times New Roman', fontSize=9.5,
    leading=14, textColor=TEXT_PRIMARY, alignment=TA_LEFT
)

cell_center = ParagraphStyle(
    name='CellCenter', fontName='Times New Roman', fontSize=9.5,
    leading=14, textColor=TEXT_PRIMARY, alignment=TA_CENTER
)

stat_style = ParagraphStyle(
    name='StatBig', fontName='Times New Roman', fontSize=20,
    leading=24, textColor=ACCENT, alignment=TA_CENTER
)

stat_label = ParagraphStyle(
    name='StatLabel', fontName='Times New Roman', fontSize=9,
    leading=12, textColor=TEXT_MUTED, alignment=TA_CENTER
)

callout_style = ParagraphStyle(
    name='CalloutBody', fontName='Times New Roman', fontSize=10,
    leading=15, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    leftIndent=12, rightIndent=8, spaceBefore=4, spaceAfter=4
)

# ── TocDocTemplate ──
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

# ── Helpers ──
def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def add_major_section(text, style):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, style, level=0),
    ]

def safe_keep(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(CONTENT_W, PAGE_H)
        total_h += h
    max_h = PAGE_H * 0.4
    if total_h <= max_h:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def make_table(data, col_ratios=None, caption=None):
    """Create a styled table with alternating rows and centered layout."""
    if col_ratios is None:
        n_cols = len(data[0]) if data else 1
        col_ratios = [1.0 / n_cols] * n_cols
    col_widths = [r * CONTENT_W for r in col_ratios]
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    elements = [Spacer(1, 18), t]
    if caption:
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(caption, caption_style))
    elements.append(Spacer(1, 18))
    return elements

def bullet(text):
    return Paragraph('<bullet>&bull;</bullet>' + text, bullet_style)

def callout_box(title, body_text):
    """Create a callout box with accent left border."""
    data = [
        [Paragraph('<b>' + title + '</b>', ParagraphStyle(
            name='CalloutTitle', fontName='Times New Roman', fontSize=10,
            leading=14, textColor=ACCENT))],
        [Paragraph(body_text, callout_style)]
    ]
    t = Table(data, colWidths=[CONTENT_W * 0.85], hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('BOX', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LINEBELOW', (0, 0), (0, 0), 0, CARD_BG),
    ]))
    return t

def stat_row(stats):
    """stats = list of (value, label) tuples"""
    cells = []
    for val, label in stats:
        cells.append(Paragraph('<b>' + val + '</b>', stat_style))
    row1 = cells[:]
    cells2 = []
    for _, label in stats:
        cells2.append(Paragraph(label, stat_label))
    data = [row1, cells2]
    n = len(stats)
    col_widths = [CONTENT_W / n] * n
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('BOX', (0, 0), (-1, -1), 1, ACCENT),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('TOPPADDING', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 4),
        ('TOPPADDING', (0, 1), (-1, 1), 2),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return t

def divider():
    return HRFlowable(width="100%", thickness=1.0, color=BORDER,
                       spaceBefore=8, spaceAfter=8)

# ═══════════════════════════════════════════════
# BUILD DOCUMENT
# ═══════════════════════════════════════════════

doc = TocDocTemplate(
    BODY_PDF,
    pagesize=A4,
    leftMargin=LEFT_MARGIN,
    rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN,
    bottomMargin=BOTTOM_MARGIN,
    title='AGI Investment Landscape August 2026',
    author='Z.ai',
    creator='Z.ai',
    subject='Comprehensive research on how companies and nations are investing in AGI through policy, geopolitics, regulation, and non-traditional approaches'
)

story = []

# ── Table of Contents ──
story.append(Paragraph('<b>Table of Contents</b>', title_style))
story.append(Spacer(1, 8))
toc = TableOfContents()
toc.levelStyles = [toc_h1, toc_h2]
story.append(toc)
story.append(Spacer(1, 12))
story.append(divider())
story.append(PageBreak())

# ═══════════════════════════════════════════════
# SECTION 1: NATIONAL AI STRATEGIES
# ═══════════════════════════════════════════════
story.extend(add_major_section('<b>1. National AI Strategies</b>', h1_style))
story.append(Paragraph(
    'Governments worldwide have elevated artificial intelligence from a technology priority to a '
    'strategic national imperative. The period from 2024 through mid-2026 has seen an unprecedented '
    'wave of legislative action, executive orders, and multibillion-dollar funding commitments '
    'designed to secure economic competitiveness, national security advantages, and technological '
    'sovereignty in the race toward artificial general intelligence.',
    body_style
))

story.append(Paragraph('<b>1.1 United States: CHIPS Act and Executive Order 14179</b>', h2_style))
story.append(Paragraph(
    'The United States has pursued a two-pronged strategy combining industrial policy with regulatory '
    'streamlining. The CHIPS and Science Act, signed into law in August 2022, authorized approximately '
    '$280 billion in total spending, of which roughly $53 billion is allocated for semiconductor '
    'manufacturing incentives and R&D. Under Section 48D, companies constructing or expanding '
    'fabrication facilities in the U.S. are eligible for a 25% Advanced Manufacturing Investment Tax '
    'Credit. The Department of Commerce announced the creation of a dedicated NIST AI Safety '
    'Institute office to evaluate frontier AI models for national security risks.',
    body_style
))
story.append(Paragraph(
    'On January 23, 2025, President Trump signed Executive Order 14179, titled "Removing Barriers to '
    'American Leadership in Artificial Intelligence." This order directed federal agencies to eliminate '
    'regulatory barriers perceived as hindering AI development, revoked the prior Biden-era AI executive '
    'order (EO 14110), and established a policy of "American AI dominance" across defense, healthcare, '
    'and economic domains. The order explicitly instructs agencies to prioritize rapid AI deployment '
    'over precautionary regulation.',
    body_style
))

tbl_data = [
    [Paragraph('<b>Policy</b>', header_cell_style),
     Paragraph('<b>Amount</b>', header_cell_style),
     Paragraph('<b>Date</b>', header_cell_style),
     Paragraph('<b>Strategic Rationale</b>', header_cell_style)],
    [Paragraph('CHIPS Act (Section 48D)', cell_style),
     Paragraph('$53B semiconductor subsidies + 25% tax credit', cell_style),
     Paragraph('Aug 2022 (enacted); ongoing awards', cell_center),
     Paragraph('Onshore advanced chip fabrication to reduce dependency on TSMC/Samsung', cell_style)],
    [Paragraph('EO 14179', cell_style),
     Paragraph('N/A (regulatory)', cell_center),
     Paragraph('Jan 23, 2025', cell_center),
     Paragraph('Remove regulatory barriers; accelerate AI deployment across agencies', cell_style)],
    [Paragraph('NIST AI Safety Institute', cell_style),
     Paragraph('~$10M annual budget (est.)', cell_center),
     Paragraph('2024-2025', cell_center),
     Paragraph('Evaluate frontier models for safety and national security risks', cell_style)],
]
story.extend(make_table(tbl_data, [0.22, 0.22, 0.18, 0.38],
    'Table 1: Key U.S. AI policy instruments, 2022-2026'))

story.append(Paragraph('<b>1.2 European Union: AI Act Enforcement</b>', h2_style))
story.append(Paragraph(
    'The EU AI Act, formally adopted in 2024, represents the world\'s most comprehensive AI regulatory '
    'framework. It establishes a risk-based classification system under which AI systems are categorized '
    'as unacceptable risk (banned), high risk (subject to strict compliance), limited risk (transparency '
    'obligations), or minimal risk (no regulation). General-purpose AI (GPAI) models, including large '
    'language models, face specific requirements including systematic risk assessments, data governance '
    'documentation, and incident reporting.',
    body_style
))
story.append(Paragraph(
    'Enforcement provisions began taking effect in phases throughout 2025, with the most significant '
    'compliance deadlines arriving in August 2026. Companies deploying high-risk AI systems in the EU '
    'market face fines of up to 35 million euros or 7% of global annual revenue, whichever is higher. '
    'The regulation has compelled major U.S. tech companies to establish dedicated EU compliance teams and '
    'to develop region-specific model evaluation pipelines. Critics argue the regulation risks creating '
    'a two-tier innovation landscape where European firms bear compliance costs that U.S. competitors '
    'do not, potentially slowing European AI development.',
    body_style
))

story.append(Paragraph('<b>1.3 India: India AI Mission</b>', h2_style))
story.append(Paragraph(
    'India approved the India AI Mission in March 2024 with a total budget outlay of 10,371.92 crore '
    'rupees (approximately $1.25 billion). The mission is structured around several pillars: building '
    'AI computing infrastructure of 10,000+ GPUs, developing India-specific datasets, funding AI startups '
    'and researchers, and establishing Centers of Excellence in AI education. The mission specifically '
    'targets building foundational models trained on India\'s 22 officially recognized languages, '
    'addressing a gap in current LLM coverage. The computing infrastructure component envisions '
    'a public-private partnership model where the government provides baseline GPU capacity and private '
    'companies contribute additional compute.',
    body_style
))

story.append(Paragraph('<b>1.4 China: Next Generation AI Development Plan</b>', h2_style))
story.append(Paragraph(
    'China\'s State Council issued the "Next Generation Artificial Intelligence Development Plan" as '
    'early as 2017, setting the ambitious goal of becoming the global AI leader by 2030. Since then, '
    'China has invested an estimated $15-20 billion annually in AI research through direct government '
    'funding, state-guided venture capital, and municipal AI industrial parks. Key entities include '
    'Baidu (Ernie Bot), Alibaba (Tongyi Qianwen), Tencent (Hunyuan), and the state-backed Beijing '
    'Academy of Artificial Intelligence. Despite U.S. semiconductor export controls restricting access '
    'to advanced NVIDIA GPUs, Chinese firms have continued to train competitive models using domestic '
    'chips from Huawei (Ascend 910B) and SMIC-manufactured alternatives. China also published '
    'interim regulations on generative AI in 2023, requiring safety assessments and content labeling '
    'for public-facing AI services.',
    body_style
))

story.append(Paragraph('<b>1.5 United Kingdom: AI Safety Institute and Frontier AI Taskforce</b>', h2_style))
story.append(Paragraph(
    'The UK established the AI Safety Institute (AISI) in November 2023, making it the first '
    'government-funded organization dedicated to evaluating frontier AI models for safety risks. '
    'The Frontier AI Taskforce, initially allocated 100 million pounds, was established to conduct '
    'cutting-edge research on AI safety and to evaluate models before public deployment. The UK '
    'hosted the first AI Safety Summit at Bletchley Park in November 2023, bringing together 28 '
    'nations to sign a declaration on AI safety cooperation. Prime Minister Rishi Sunak subsequently '
    'announced increased funding for AI safety research, and the UK has positioned itself as a '
    'neutral convening power between the more aggressive U.S. approach and the more regulatory '
    'EU framework.',
    body_style
))

story.append(Paragraph('<b>1.6 Japan: AI Strategy Council and Moonshot Program</b>', h2_style))
story.append(Paragraph(
    'Japan\'s approach to AI investment emphasizes industrial automation and supercomputing '
    'infrastructure. The Ministry of Economy, Trade and Industry (METI) established the AI Strategy '
    'Council to coordinate national AI policy, while the government\'s Moonshot R&D Program funds '
    'ambitious long-term AI research goals including the development of AI systems that can learn '
    'and reason autonomously. Japan has invested significantly in AI computing infrastructure through '
    'its National Institute of Advanced Industrial Science and Technology (AIST) and partnerships with '
    'NVIDIA and domestic chip manufacturers. The country\'s aging demographics make AI-driven '
    'automation a matter of economic survival, not merely technological ambition.',
    body_style
))

story.append(stat_row([
    ('$280B', 'U.S. CHIPS Act\n(Total Authorized)'),
    ('$1.25B', 'India AI Mission\n(Approved Mar 2024)'),
    ('$15-20B/yr', 'China AI\nAnnual Investment'),
    ('100M GBP', 'UK Frontier AI\nTaskforce'),
]))

story.append(Spacer(1, 18))

# ═══════════════════════════════════════════════
# SECTION 2: SOVEREIGN AI / NATIONAL CHAMPIONS
# ═══════════════════════════════════════════════
story.extend(add_major_section('<b>2. Sovereign AI and National Champions</b>', h1_style))
story.append(Paragraph(
    'As AI becomes a critical layer of national infrastructure, governments and investors are '
    'backing "national champion" AI companies to ensure technological sovereignty. These entities '
    'receive preferential access to government contracts, computing resources, and regulatory '
    'support in exchange for building AI capabilities that serve national interests.',
    body_style
))

story.append(Paragraph('<b>2.1 Mistral AI (France)</b>', h2_style))
story.append(Paragraph(
    'Mistral AI, founded in Paris in 2023, has rapidly become Europe\'s most prominent AI company '
    'and a cornerstone of France\'s sovereign AI strategy. The company raised a Series B of 640 million '
    'euros (approximately $690 million) in June 2024 at a valuation of roughly 6 billion euros, '
    'making it one of Europe\'s most valuable startups. Backers include French telecom giant Bouygues, '
    'BNP Paribas, and the French government through its sovereign wealth vehicle. Mistral\'s open-weight '
    'model releases and strong multilingual capabilities (particularly in French and other European '
    'languages) have positioned it as the credible European alternative to OpenAI\'s GPT series '
    'and Google\'s Gemini. The French government has signaled that Mistral will play a central role '
    'in public-sector AI deployment and national AI infrastructure.',
    body_style
))

story.append(Paragraph('<b>2.2 Sakana AI (Japan)</b>', h2_style))
story.append(Paragraph(
    'Sakana AI, founded in Tokyo in 2023 by former Google researchers David Ha and Llion Jones, '
    'represents Japan\'s entry into the frontier AI race. The company focuses on nature-inspired AI '
    'approaches, including evolutionary algorithms and neural architecture search, and has gained '
    'attention for its Darwin Godel Machine research on self-improving AI systems. Sakana raised '
    'approximately $200 million across seed and Series A rounds, with backing from Japanese investors '
    'including NTT, Sony, and several Japanese venture capital firms. The company\'s research has '
    'accumulated over 175 academic citations, lending it scientific credibility alongside its '
    'commercial ambitions. Sakana\'s approach is notably distinct from the scaling-centric paradigm '
    'dominant in U.S. AI labs, focusing instead on algorithmic efficiency and evolutionary optimization.',
    body_style
))

story.append(Paragraph('<b>2.3 G42 and MGX (United Arab Emirates)</b>', h2_style))
story.append(Paragraph(
    'The United Arab Emirates has pursued one of the most aggressive sovereign AI strategies in the '
    'world through G42, an AI conglomerate chaired by Sheikh Tahnoon bin Zayed Al Nahyan (the UAE '
    'national security advisor). G42 operates subsidiaries spanning cloud computing (Core42), '
    'healthcare AI, semiconductors, and autonomous systems. In 2024-2025, G42 underwent a strategic '
    'restructuring that included a $1.5 billion investment from Microsoft and a pivot away from Chinese '
    'technology partners (including Huawei) toward U.S.-based systems, reportedly in exchange for '
    'relaxed U.S. export control restrictions on advanced chips.',
    body_style
))
story.append(Paragraph(
    'MGX, a state-backed investment vehicle co chaired by Sheikh Tahnoon and Mubadala\'s CEO, '
    'was established to manage AI-focused sovereign wealth. MGX is a key partner in the Stargate '
    'Project (discussed in Section 4), committing capital alongside SoftBank and Oracle. The UAE\'s '
    'strategy positions it as a neutral technology broker between the U.S. and China, leveraging '
    'its capital and geopolitical position to build a sovereign AI ecosystem that serves both '
    'domestic modernization goals and global influence.',
    body_style
))

tbl2 = [
    [Paragraph('<b>Entity</b>', header_cell_style),
     Paragraph('<b>Country</b>', header_cell_style),
     Paragraph('<b>Key Funding</b>', header_cell_style),
     Paragraph('<b>Strategic Focus</b>', header_cell_style)],
    [Paragraph('Mistral AI', cell_style),
     Paragraph('France', cell_center),
     Paragraph('Series B: EUR 640M (~$690M), Jun 2024', cell_style),
     Paragraph('Open-weight multilingual LLMs; European GPT alternative', cell_style)],
    [Paragraph('Sakana AI', cell_style),
     Paragraph('Japan', cell_center),
     Paragraph('~$200M seed + Series A, 2023-2024', cell_style),
     Paragraph('Evolutionary AI, nature-inspired algorithms', cell_style)],
    [Paragraph('G42 / MGX', cell_style),
     Paragraph('UAE', cell_center),
     Paragraph('$1.5B from Microsoft + sovereign capital', cell_style),
     Paragraph('AI conglomerate spanning cloud, health, semiconductors', cell_style)],
]
story.extend(make_table(tbl2, [0.15, 0.10, 0.30, 0.45],
    'Table 2: Sovereign AI national champions, 2024-2026'))

# ═══════════════════════════════════════════════
# SECTION 3: REGULATORY & COMPLIANCE INVESTMENT
# ═══════════════════════════════════════════════
story.extend(add_major_section('<b>3. Regulatory and Compliance Investment</b>', h1_style))
story.append(Paragraph(
    'The acceleration of AI capabilities has triggered a parallel acceleration in regulatory activity. '
    'Companies and governments are investing billions in compliance infrastructure, model evaluation '
    'frameworks, and regulatory technology to keep pace with the rapid deployment of AI systems.',
    body_style
))

story.append(Paragraph('<b>3.1 EU AI Act Compliance Industry</b>', h2_style))
story.append(Paragraph(
    'The EU AI Act has created an entirely new compliance industry. Companies deploying AI systems '
    'in European markets must invest in conformity assessments, data governance audits, and ongoing '
    'monitoring systems. Major consulting firms including PwC, Deloitte, and Accenture have established '
    'dedicated AI Act compliance practices, collectively estimated to represent a market opportunity '
    'exceeding 2 billion euros annually by 2027. Startups specializing in AI compliance tooling, '
    'such as Holistic AI, LatticeFlow, and Fairly AI, have raised significant venture capital to build '
    'automated compliance platforms. The Act\'s August 2026 enforcement deadline for high-risk AI '
    'systems has driven a surge in demand for legal, technical, and organizational readiness assessments.',
    body_style
))

story.append(Paragraph('<b>3.2 U.S. State-Level AI Legislation</b>', h2_style))
story.append(Paragraph(
    'In the absence of comprehensive federal AI legislation (following the revocation of EO 14110), '
    'U.S. states have enacted a patchwork of AI regulations. California, Colorado, and several other '
    'states have passed laws targeting specific AI applications including algorithmic hiring decisions, '
    'insurance underwriting, and deepfake regulation. Colorado\'s SB 24-205, signed in May 2024, '
    'requires "reasonable care" in the deployment of high-risk AI systems and takes effect in February '
    '2026. The fragmented regulatory landscape has forced AI companies to develop multi-state '
    'compliance strategies, with estimated compliance costs ranging from $2-5 million per company '
    'for firms operating nationally. This fragmentation is widely cited as a driver of the push for '
    'federal preemption legislation.',
    body_style
))

story.append(Paragraph('<b>3.3 Corporate AI Governance Investment</b>', h2_style))
story.append(Paragraph(
    'Major corporations have established internal AI governance boards, risk committees, and '
    'dedicated responsible AI teams. Microsoft created its Office of Responsible AI, Google maintains '
    'its Responsible AI and Human-Centered Technology team, and Meta established its Responsible AI '
    'team under the broader AI organization. Enterprise spending on AI governance tooling, including '
    'model monitoring, bias detection, and audit trail systems, is estimated to reach $3.5 billion '
    'globally in 2025-2026. Companies like Arthur AI, Fiddler AI, and Credo AI have raised venture '
    'capital to serve this growing market. The investment reflects both genuine risk management concerns '
    'and the need to demonstrate regulatory readiness to customers, partners, and government auditors.',
    body_style
))

# ═══════════════════════════════════════════════
# SECTION 4: GEOPOLITICAL CHIPS WAR
# ═══════════════════════════════════════════════
story.extend(add_major_section('<b>4. Geopolitical Chips War</b>', h1_style))
story.append(Paragraph(
    'Advanced semiconductors have become the defining strategic resource of the AI era. Control over '
    'chip design, manufacturing, and supply chains determines which nations can train and deploy '
    'frontier AI models. The resulting geopolitical competition over chips has produced massive '
    'investment programs, export controls, and strategic industrial policy interventions.',
    body_style
))

story.append(Paragraph('<b>4.1 U.S. Semiconductor Export Controls</b>', h2_style))
story.append(Paragraph(
    'The U.S. Bureau of Industry and Security (BIS) has imposed increasingly aggressive export '
    'controls on advanced semiconductors and chipmaking equipment since October 2022. These controls '
    'restrict the sale of NVIDIA\'s H100, H200, and Blackwell-series GPUs to China and certain other '
    'countries of concern, and limit the ability of ASML (Netherlands) to sell EUV (extreme ultraviolet) '
    'lithography machines to Chinese semiconductor manufacturers. The controls have been expanded '
    'through updates in October 2023 and 2024, closing loopholes through which Chinese firms accessed '
    'chips via third countries.',
    body_style
))
story.append(Paragraph(
    'The controls target China\'s SMIC (Semiconductor Manufacturing International Corporation), '
    'preventing it from advancing beyond 7nm process nodes without access to EUV lithography. Despite '
    'these restrictions, reports indicate SMIC has achieved limited production of 5nm chips for Huawei\'s '
    'Mate 60 series using older DUV equipment, though at significantly higher cost and lower yields. '
    'The effectiveness of export controls remains debated: while they have slowed China\'s chip '
    'advancement, they have also accelerated China\'s push for self-sufficiency, with massive government '
    'investment in domestic alternatives.',
    body_style
))

story.append(Paragraph('<b>4.2 TSMC Arizona Fabs</b>', h2_style))
story.append(Paragraph(
    'Taiwan Semiconductor Manufacturing Company (TSMC), which fabricates approximately 90% of the '
    'world\'s most advanced chips, has committed to building three fabrication facilities in Phoenix, '
    'Arizona. The total investment for all three fabs is estimated at over $165 billion, making it '
    'the largest foreign direct investment in U.S. manufacturing history. Fab 1 (N4 process) began '
    'volume production in 2025. Fab 2 (N3 process) is under construction with anticipated production '
    'beginning in 2028. Fab 3 (N2 or more advanced process) was announced in 2025.',
    body_style
))
story.append(Paragraph(
    'The project has faced significant challenges including labor shortages, cultural conflicts between '
    'Taiwanese and American workers, and construction cost overruns exceeding $4 billion. Nevertheless, '
    'the strategic importance of onshore advanced chip manufacturing is clear: in the event of a '
    'Taiwan Strait crisis, the U.S. would have access to domestic production of chips critical to AI, '
    'defense, and telecommunications systems. TSMC has also announced plans for fabs in Japan (Kumamoto, '
    'with Sony and Toyota partnerships) and Europe (Dresden, with Bosch, Infineon, and NXP), as part '
    'of a broader geographic diversification strategy.',
    body_style
))

story.append(Paragraph('<b>4.3 The Stargate Project ($500B AI Infrastructure)</b>', h2_style))
story.append(Paragraph(
    'Announced in January 2025, the Stargate Project is a $500 billion joint venture to build '
    'massive AI computing infrastructure in the United States. The project\'s founding partners include '
    'OpenAI, SoftBank, Oracle, and MGX (the UAE sovereign investment vehicle). The initial commitment '
    'is $100 billion, with the full $500 billion expected to be deployed over four years. Stargate plans '
    'to build data centers of unprecedented scale, housing hundreds of thousands of advanced GPUs, '
    'to train next-generation AI models.',
    body_style
))
story.append(Paragraph(
    'Microsoft, which had been OpenAI\'s exclusive cloud partner, initially disputed the project\'s '
    'framing before agreeing to participate. The strategic rationale extends beyond raw compute: '
    'Stargate is designed to ensure that the physical infrastructure for frontier AI development '
    'remains within U.S. borders, reducing dependency on international cloud providers and creating '
    'American jobs in construction, engineering, and operations. The project also carries geopolitical '
    'significance as a demonstration of American commitment to AI leadership, particularly vis-a-vis '
    'China\'s own infrastructure buildout.',
    body_style
))

story.append(stat_row([
    ('$500B', 'Stargate Project\n(Jan 2025)'),
    ('$165B+', 'TSMC Arizona\n(3 Fabs)'),
    ('$53B', 'U.S. CHIPS Act\n(Semiconductors)'),
    ('$1.5B', 'Microsoft in G42\n(Strategic Pivot)'),
]))

story.append(Spacer(1, 18))

# ═══════════════════════════════════════════════
# SECTION 5: EXOTIC / FRONTIER APPROACHES
# ═══════════════════════════════════════════════
story.extend(add_major_section('<b>5. Exotic and Frontier Approaches</b>', h1_style))
story.append(Paragraph(
    'Beyond mainstream large language model scaling, researchers and investors are pursuing radically '
    'different approaches to achieving artificial general intelligence. These frontier approaches '
    'span quantum computing, brain-computer interfaces, biocomputing, and novel machine learning '
    'paradigms that could bypass the computational bottlenecks of current transformer architectures.',
    body_style
))

story.append(Paragraph('<b>5.1 Quantum Computing for AI</b>', h2_style))
story.append(Paragraph(
    'Quantum computing promises exponential speedups for certain classes of AI-relevant computations, '
    'including optimization, sampling, and linear algebra. IBM has committed over $10 billion to its '
    'quantum roadmap through 2033, targeting 100,000+ qubit systems. IonQ, a trapped-ion quantum '
    'computing company, has gone public (NYSE: IONQ) and made strategic acquisitions to expand its '
    'quantum AI capabilities. Google\'s Willow quantum processor demonstrated error correction '
    'breakthroughs in 2024, reaching below the quantum error correction threshold for the first time. '
    'Microsoft\'s topological qubit approach, pursued through its Azure Quantum program, aims to '
    'create more stable qubits for practical quantum machine learning applications.',
    body_style
))
story.append(Paragraph(
    'The intersection of quantum computing and AI remains largely pre-commercial, but investment has '
    'accelerated based on the premise that quantum advantage could enable training of vastly more '
    'efficient AI models or enable AI to solve problems fundamentally intractable for classical '
    'computers. Key milestones targeted include logical qubit demonstrations (error-corrected qubits '
    'composed of multiple physical qubits) by 2026-2028 and quantum advantage on commercially '
    'relevant AI tasks by 2030-2035.',
    body_style
))

story.append(Paragraph('<b>5.2 Brain-Computer Interfaces</b>', h2_style))
story.append(Paragraph(
    'Brain-computer interface (BCI) technology has advanced rapidly, driven by significant investment '
    'and clinical breakthroughs. Neuralink, founded by Elon Musk, has raised approximately $1.29 billion '
    'in total funding and implanted its N1 device in multiple human patients as of 2025-2026. The company '
    'has set a goal of implanting devices in over 1,000 patients and aims to eventually enable direct '
    'brain-to-computer communication for a wide range of applications including communication for '
    'paralyzed patients, memory enhancement, and potential brain-AI interfaces.',
    body_style
))
story.append(Paragraph(
    'Competitors include Synchron (backed by Gates and Bezos), which uses a stent-based electrode '
    'approach that does not require open brain surgery, and Paradromics, which is developing high-bandwidth '
    'BCIs for clinical applications. The U.S. Defense Advanced Research Projects Agency (DARPA) has '
    'funded BCI research through its Neural Engineering System Design (NESD) program. The investment '
    'thesis for AGI relevance is that understanding and interfacing with biological neural systems '
    'could provide insights into achieving artificial general intelligence, and that BCIs could '
    'eventually enable hybrid human-AI cognition.',
    body_style
))

story.append(Paragraph('<b>5.3 Organoid Intelligence (Biocomputing)</b>', h2_style))
story.append(Paragraph(
    'Organoid intelligence represents a radical departure from silicon-based computing. The National '
    'Science Foundation (NSF) awarded a $14 million grant in 2023-2024 to a multi-university consortium '
    'to develop brain organoid biocomputing systems. Brain organoids are three-dimensional cultures '
    'of human neural cells that exhibit basic electrical activity and rudimentary learning behaviors. '
    'Researchers at Johns Hopkins University and other institutions are working to interface these '
    'biological neural networks with electronic systems, creating hybrid bio-digital computing '
    'architectures.',
    body_style
))
story.append(Paragraph(
    'Proponents argue that biological neural networks operate at energy efficiencies millions of '
    'times greater than silicon chips, and that understanding how biological systems achieve general '
    'intelligence could inform AGI development. Critics note that current brain organoids are far '
    'too simple to perform useful computation and raise significant ethical questions about creating '
    'sentient or semi-sentient biological systems. The field remains at an early research stage, but '
    'the NSF funding signals serious institutional interest in biologically-inspired computing paradigms.',
    body_style
))

story.append(Paragraph('<b>5.4 Darwin Godel Machine (Sakana AI)</b>', h2_style))
story.append(Paragraph(
    'Sakana AI\'s Darwin Godel Machine represents a novel approach to self-improving AI. The system '
    'combines evolutionary computation with formal verification to create AI systems that can modify '
    'their own architecture and objectives in a provably safe manner. Unlike conventional approaches '
    'where model architecture is fixed by human designers, the Darwin Godel Machine allows the AI '
    'to propose modifications to its own code, evaluate those modifications against a formal '
    'correctness criterion (inspired by Godel\'s incompleteness theorems), and accept only those '
    'changes that can be proven not to degrade performance.',
    body_style
))
story.append(Paragraph(
    'The research has garnered over 175 citations in the academic literature and has been presented '
    'at major AI conferences. The approach addresses a fundamental challenge in AGI safety: how to '
    'create AI systems more capable than their creators while ensuring those systems remain '
    'controllable and aligned with human intentions. The Darwin Godel Machine demonstrates that '
    'algorithmic innovation, rather than raw scaling, may be a viable path toward AGI, and Japan\'s '
    'investment in Sakana AI reflects a strategic bet on this alternative paradigm.',
    body_style
))

story.append(Paragraph('<b>5.5 Whole Brain Emulation and Connectomics</b>', h2_style))
story.append(Paragraph(
    'Whole brain emulation (WBE) and connectomics represent the long-term frontier of AGI research. '
    'Eon Systems, a startup working on whole brain emulation, has focused on mapping and simulating '
    'the complete neural connectivity of simple organisms, beginning with the fruit fly (Drosophila '
    'melanogaster), which has approximately 100,000 neurons. The field of connectomics, which maps the '
    'complete wiring diagram of nervous systems, has been advanced by major projects including the '
    'Allen Institute for Brain Science\'s mouse brain connectome and Google\'s collaboration with '
    'Princeton University on electron microscopy-based neural reconstruction.',
    body_style
))
story.append(Paragraph(
    'While full human brain emulation (approximately 86 billion neurons) remains far beyond current '
    'technological capabilities, the intermediate goal of simulating simpler organisms provides '
    'valuable data about how biological intelligence emerges from neural circuits. Investment in this '
    'area is driven by the premise that understanding the computational principles of biological brains '
    'is essential for building artificial general intelligence, rather than relying solely on '
    'engineering approaches based on transformer architectures.',
    body_style
))

tbl3 = [
    [Paragraph('<b>Approach</b>', header_cell_style),
     Paragraph('<b>Key Entities</b>', header_cell_style),
     Paragraph('<b>Investment</b>', header_cell_style),
     Paragraph('<b>AGI Relevance</b>', header_cell_style)],
    [Paragraph('Quantum Computing', cell_style),
     Paragraph('IBM, IonQ, Google, Microsoft', cell_style),
     Paragraph('IBM: $10B+ through 2033', cell_style),
     Paragraph('Exponential speedups for optimization and sampling', cell_style)],
    [Paragraph('Brain-Computer Interfaces', cell_style),
     Paragraph('Neuralink, Synchron, Paradromics', cell_style),
     Paragraph('Neuralink: $1.29B total', cell_style),
     Paragraph('Hybrid human-AI cognition; neural understanding', cell_style)],
    [Paragraph('Organoid Intelligence', cell_style),
     Paragraph('Johns Hopkins, NSF consortium', cell_style),
     Paragraph('NSF: $14M grant', cell_style),
     Paragraph('Bio-digital computing; energy-efficient neural networks', cell_style)],
    [Paragraph('Darwin Godel Machine', cell_style),
     Paragraph('Sakana AI (Japan)', cell_style),
     Paragraph('~$200M (company funding)', cell_style),
     Paragraph('Self-improving AI with formal safety guarantees', cell_style)],
    [Paragraph('Whole Brain Emulation', cell_style),
     Paragraph('Eon Systems, Allen Institute, Google', cell_style),
     Paragraph('Various (public + private)', cell_style),
     Paragraph('Reverse-engineering biological intelligence', cell_style)],
]
story.extend(make_table(tbl3, [0.18, 0.22, 0.20, 0.40],
    'Table 3: Exotic and frontier AGI approaches, 2024-2026'))

# ═══════════════════════════════════════════════
# SECTION 6: AGI SAFETY / EXISTENTIAL RISK
# ═══════════════════════════════════════════════
story.extend(add_major_section('<b>6. AGI Safety and Existential Risk</b>', h1_style))
story.append(Paragraph(
    'As AI capabilities advance toward AGI, the field of AI safety has grown from a niche academic '
    'concern to a major investment and policy priority. Governments, corporations, and philanthropic '
    'organizations are dedicating increasing resources to understanding and mitigating the risks '
    'posed by highly capable AI systems.',
    body_style
))

story.append(Paragraph('<b>6.1 OpenAI and Anthropic Safety Investments</b>', h2_style))
story.append(Paragraph(
    'OpenAI and Anthropic, the two leading developers of frontier AI models, have invested heavily in '
    'safety research. Anthropic was founded in 2021 with an explicit focus on AI safety, and its '
    'Constitutional AI approach trains models to follow a set of principles designed to prevent harmful '
    'outputs. Anthropic has raised over $9 billion in total funding, most recently at a valuation of '
    'approximately $965 billion following Amazon\'s $4 billion investment in late 2024, making it '
    'one of the most valuable private companies in the world. OpenAI established its Superalignment '
    'team (subsequently restructured) to develop techniques for ensuring that superhuman AI systems '
    'remain aligned with human intentions. Both companies dedicate roughly 20-30% of their compute '
    'budgets to safety research and red-teaming efforts.',
    body_style
))

story.append(Paragraph('<b>6.2 UK AI Safety Institute (AISI)</b>', h2_style))
story.append(Paragraph(
    'The UK AISI, established in November 2023, was the first government-funded organization dedicated '
    'to evaluating frontier AI models for safety risks before public deployment. The institute conducts '
    'pre-deployment safety evaluations of models from major AI companies including OpenAI, Anthropic, '
    'Google DeepMind, and Meta. Its work focuses on identifying dangerous capabilities in AI systems, '
    'including the ability to autonomously replicate, deceive humans, or develop dangerous tools. '
    'The AISI has published evaluation frameworks and testing methodologies that are being adopted '
    'as industry standards. The institute\'s budget has grown from initial seed funding to a sustained '
    'annual allocation, and it has established partnerships with similar initiatives in the U.S., EU, '
    'Canada, and Japan.',
    body_style
))

story.append(Paragraph('<b>6.3 Philanthropic AI Safety Funding</b>', h2_style))
story.append(Paragraph(
    'Philanthropic organizations have played a critical role in funding AI safety research. The '
    'Effective Altruism community, through organizations like the Open Philanthropy Project, has '
    'directed hundreds of millions of dollars toward AI safety research grants, supporting academic '
    'researchers, think tanks, and nonprofit organizations. The Machine Intelligence Research Institute '
    '(MIRI), the Center for Human-Compatible AI (CHAI) at UC Berkeley, and the Future of Humanity '
    'Institute (FHI) at Oxford University have been major recipients. Individual donors including '
    'Jaume Altisent, Paul Christiano, and former OpenAI researcher Jan Leike have also contributed '
    'significantly. The total philanthropic investment in AI safety is estimated at $500 million to '
    '$1 billion cumulatively through 2026.',
    body_style
))

story.append(callout_box(
    'Key Safety Metric',
    'Anthropic\'s valuation reached $965 billion following Amazon\'s $4B investment, '
    'reflecting the market\'s assessment that AI safety capabilities are a core competitive '
    'advantage, not merely a regulatory checkbox.'
))

story.append(Spacer(1, 12))

# ═══════════════════════════════════════════════
# SECTION 7: DEFENSE & NATIONAL SECURITY
# ═══════════════════════════════════════════════
story.extend(add_major_section('<b>7. Defense and National Security</b>', h1_style))
story.append(Paragraph(
    'Military and intelligence agencies worldwide are investing heavily in AI for defense '
    'applications, from autonomous weapons systems to intelligence analysis and cybersecurity. '
    'The integration of AI into national security infrastructure has become a top priority for '
    'defense establishments across NATO and beyond.',
    body_style
))

story.append(Paragraph('<b>7.1 Pentagon Replicator Initiative</b>', h2_style))
story.append(Paragraph(
    'The Pentagon\'s Replicator initiative, launched in August 2023 by Deputy Secretary of Defense '
    'Kathleen Hicks, aims to deploy thousands of autonomous systems within 18-24 months to counter '
    'China\'s military mass advantage. The initiative has a budget of approximately $1 billion and '
    'focuses on affordable, attritable autonomous drones, uncrewed surface vessels, and AI-guided '
    'munitions. The program has two phases: Replicator 1 (focused on countering mass in the Indo-Pacific) '
    'and Replicator 2 (focused on countering mass in Europe). Key contractors include Anduril Industries, '
    'Shield AI, and several smaller autonomous systems startups.',
    body_style
))
story.append(Paragraph(
    'The strategic rationale is clear: autonomous AI systems can be produced at a fraction of the '
    'cost of traditional manned platforms, allowing the U.S. to offset China\'s numerical advantages '
    'in ships, aircraft, and personnel. The initiative also drives investment in AI-powered command '
    'and control systems, computer vision for target identification, and AI-enabled electronic warfare.',
    body_style
))

story.append(Paragraph('<b>7.2 NATO Innovation Fund</b>', h2_style))
story.append(Paragraph(
    'NATO established a dedicated Innovation Fund with capital exceeding 1 billion euros, backed by '
    '24 allied nations. The fund invests in dual-use technology startups across AI, quantum '
    'technology, biotechnology, and space systems, with a particular focus on AI applications '
    'relevant to alliance security. The fund makes venture-stage investments in companies developing '
    'AI-powered threat detection, autonomous systems, cybersecurity tools, and satellite imagery '
    'analysis. It represents a novel approach for a defense alliance, shifting from traditional '
    'procurement to startup-style venture investing. The fund complements NATO\'s DIANA (Defense '
    'Innovation Accelerator for the North Atlantic) network of regional acceleration offices and '
    'test centers spanning North America and Europe.',
    body_style
))

story.append(stat_row([
    ('$1B', 'Pentagon Replicator\n(Autonomous Systems)'),
    ('EUR 1B+', 'NATO Innovation Fund\n(24 Allies)'),
    ('$10B+', 'IBM Quantum Roadmap\n(through 2033)'),
]))

story.append(Spacer(1, 18))

# ═══════════════════════════════════════════════
# SECTION 8: FINANCIAL MARKETS & SPECULATION
# ═══════════════════════════════════════════════
story.extend(add_major_section('<b>8. Financial Markets and AI Speculation</b>', h1_style))
story.append(Paragraph(
    'The race toward AGI has created a financial phenomenon of historic proportions, with massive '
    'venture capital flows, soaring startup valuations, and intense debate about whether the AI '
    'investment boom represents sustainable value creation or a speculative bubble.',
    body_style
))

story.append(Paragraph('<b>8.1 AI Startup Valuations and Mega-Rounds</b>', h2_style))
story.append(Paragraph(
    'AI startup valuations have reached unprecedented levels. Anthropic, the AI safety-focused company '
    'founded by former OpenAI executives, achieved a valuation of approximately $965 billion in late '
    '2024 following Amazon\'s $4 billion investment, making it one of the most valuable private companies '
    'globally. Cursor, the AI-powered code editor company, reached a valuation of $29.3 billion in '
    '2025 following its Series B round. OpenAI, the developer of the GPT series, has been valued '
    'at over $300 billion following its conversion to a for-profit entity and SoftBank\'s multibillion-dollar '
    'investment. xAI, Elon Musk\'s AI company, raised $6 billion in a single round in 2025.',
    body_style
))
story.append(Paragraph(
    'Global venture capital investment in AI companies reached approximately $258.7 billion in 2025, '
    'representing a dramatic increase from $49 billion in 2022. The concentration of investment in '
    'a small number of frontier model companies has raised concerns about market concentration and '
    'whether returns can justify the capital deployed. NVIDIA, whose GPUs are the de facto standard '
    'for AI training, has seen its market capitalization exceed $3 trillion, with the company involved '
    'in over $750 billion in AI-related deals and partnerships.',
    body_style
))

story.append(Paragraph('<b>8.2 The AI Bubble Debate</b>', h2_style))
story.append(Paragraph(
    'The question of whether AI investment constitutes a speculative bubble dominates financial discourse. '
    'Proponents of the bubble thesis point to several warning signs: massive capital deployment with '
    'limited revenue to justify valuations (many AI companies burn billions annually), a surge in AI-themed '
    'IPO filings of uncertain quality, and historical parallels to the dot-com bubble of 1999-2000. '
    'Skeptics note that unlike the dot-com era, leading AI companies (OpenAI, Anthropic) generate '
    'billions in annual revenue with rapid growth trajectories, and that the underlying technology '
    'demonstrates genuine transformative capability.',
    body_style
))
story.append(Paragraph(
    'The debate has implications for policy: if AI investment is a bubble, governments may be '
    'overinvesting in infrastructure (like the Stargate Project) that could become stranded assets. '
    'If the boom is sustainable, underinvestment in AI infrastructure could cede competitive '
    'advantage to rivals. The resolution of this debate will likely determine the trajectory of '
    'AI investment for the remainder of the decade. What is clear is that the scale of financial '
    'commitment to AI, regardless of its ultimate sustainability, reflects a genuine global consensus '
    'that artificial general intelligence will be the defining technology of the 21st century.',
    body_style
))

tbl4 = [
    [Paragraph('<b>Company</b>', header_cell_style),
     Paragraph('<b>Valuation</b>', header_cell_style),
     Paragraph('<b>Key Investors</b>', header_cell_style),
     Paragraph('<b>Date</b>', header_cell_style)],
    [Paragraph('Anthropic', cell_style),
     Paragraph('~$965B', cell_center),
     Paragraph('Amazon ($4B), Google, others', cell_style),
     Paragraph('Late 2024', cell_center)],
    [Paragraph('OpenAI', cell_style),
     Paragraph('$300B+', cell_center),
     Paragraph('SoftBank, Microsoft, Thrive', cell_style),
     Paragraph('2025', cell_center)],
    [Paragraph('xAI', cell_style),
     Paragraph('$50B+ (est.)', cell_center),
     Paragraph('Sequoia, a16z, $6B round', cell_style),
     Paragraph('2025', cell_center)],
    [Paragraph('Cursor', cell_style),
     Paragraph('$29.3B', cell_center),
     Paragraph('Thrive Capital, a16z', cell_style),
     Paragraph('2025', cell_center)],
    [Paragraph('NVIDIA', cell_style),
     Paragraph('$3T+ market cap', cell_center),
     Paragraph('Public (NASDAQ: NVDA)', cell_style),
     Paragraph('2025-2026', cell_center)],
]
story.extend(make_table(tbl4, [0.15, 0.15, 0.40, 0.15],
    'Table 4: Major AI company valuations and funding, 2024-2026'))

# ═══════════════════════════════════════════════
# CONCLUSION
# ═══════════════════════════════════════════════
story.extend(add_major_section('<b>9. Conclusion: The AGI Investment Landscape</b>', h1_style))
story.append(Paragraph(
    'The investment landscape surrounding artificial general intelligence as of August 2026 is '
    'characterized by five defining features. First, the scale of commitment is unprecedented: '
    'governments and corporations are deploying hundreds of billions of dollars across semiconductor '
    'manufacturing, AI infrastructure, frontier model development, and safety research. Second, '
    'the geographic scope is truly global: every major economic bloc, from the U.S. and EU to China, '
    'India, Japan, and the UAE, has developed explicit national AI strategies with dedicated '
    'funding. Third, the competitive dynamic is intensifying: export controls, regulatory barriers, '
    'and sovereign AI champions reflect a world where AI capability is viewed as essential to '
    'national security and economic competitiveness.',
    body_style
))
story.append(Paragraph(
    'Fourth, the diversity of approaches is notable: while large language model scaling remains '
    'the dominant paradigm, significant investment flows to quantum computing, brain-computer '
    'interfaces, biocomputing, evolutionary AI, and whole brain emulation. These frontier '
    'approaches represent high-risk, high-reward bets on fundamentally different paths to AGI. '
    'Fifth, the financial dimension has become inseparable from the technological: startup '
    'valuations, venture capital flows, and public market capitalizations reflect both genuine '
    'confidence in AI\'s transformative potential and the speculative dynamics that accompany any '
    'major technological transition.',
    body_style
))
story.append(Paragraph(
    'What remains uncertain is whether the current investment intensity is proportional to the '
    'probability and timeline of achieving artificial general intelligence. Optimists believe '
    'AGI could emerge within 5-10 years, justifying current investment levels. Skeptics argue '
    'that fundamental breakthroughs beyond scaling may be required, potentially pushing AGI '
    'decades into the future. Regardless of which view proves correct, the investments documented '
    'in this report have already transformed the global technology landscape, reshaping '
    'semiconductor supply chains, regulatory frameworks, defense strategies, and financial '
    'markets in ways that will persist for decades to come.',
    body_style
))

story.append(Spacer(1, 24))
story.append(divider())
story.append(Spacer(1, 12))
story.append(Paragraph(
    '<i>Report compiled August 2026. Data sourced from public disclosures, regulatory filings, '
    'and verified media reports. All figures represent best-available estimates at time of writing.</i>',
    ParagraphStyle(name='Disclaimer', fontName='Times New Roman', fontSize=8.5,
                   leading=13, alignment=TA_LEFT, textColor=TEXT_MUTED)
))

# ── Build ──
doc.multiBuild(story)
print(f"Body PDF generated: {BODY_PDF}")
