#!/usr/bin/env python3
"""Verification overlay for painting_b2b_accounts (lane P-PAINTING-B2B-LEADS-20260905).

Run AFTER tools/ingest_manual_leads.py. Upserts the same 55 account_ids with:
verified phones, corrected websites, normalized APPROACH tags, RELEVANCE 1-10,
PRIORITY P1/P2/P3, stage=researched, and score_inputs for b2b_account_score.

Verification pass: 2026-09-05, web-checked per company (evidence in notes + lane report).
business_name values MUST stay byte-identical to ingest_manual_leads.py (slug = account_id).

Run: PYTHONPATH=<repo-root> python3 tools/update_verified_leads.py
Upsert — safe to re-run. No schema changes. No network I/O.
"""
import os, sys
from datetime import datetime, timezone
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from ofn.adapters.lead_store import LeadStore

TENANT = "lead"

def _db():
    p = os.environ.get("OFN_PAINTING_DB")
    if p: return p
    d = Path.home() / ".local/share/ofn/painting.sqlite"
    return str(d) if d.exists() else str(Path(__file__).resolve().parent.parent / "painting.sqlite")

LEADS = [
    # ══ STRATA ══
    {"business_name": "RD Facilities Management", "segment": "strata", "suburb": "Seven Hills", "service_area": "Sydney metropolitan area, NSW", "website": "https://rdfm.com.au", "contact_channel": "1800 507 552 | admin@rdfm.com.au", "evidence_url": "https://rdfm.com.au", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.7, "G": 1.0, "M": 0.8, "E": 0.7, "R": 0.85, "risk": 0.1, "cost": 0.15},
     "next_action": "Pitch painting as their subcontracted trade under FM maintenance arm",
     "notes": "RELEVANCE: 8/10. APPROACH: Subcontractor Pathway. PRIORITY: P1. VERIFIED 2026-09-05: FM provider (not strata mgr), real, phone on site. Painting NOT in advertised services — they subcontract it. 'est 2010/250+ sites' NOT shown on site (unverified). ACTION: pitch as their painting subcontractor."},
    {"business_name": "Bright and Duggan Group", "segment": "strata", "suburb": "St Leonards", "service_area": "Sydney", "website": "https://bright-duggan.com.au", "contact_channel": "1300 092 863 (after-hours line) | customercare@bright-duggan.com.au", "evidence_url": "https://bright-duggan.com.au", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.95, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Contact St Leonards HQ re maintenance-contractor supplier list",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct or Vendor Panel. PRIORITY: P1. VERIFIED 2026-09-05: est 1977, 150k+ lots, explicitly manages repairs/contractors. Subsidiary of Johns Lyng Group (internal tradie preference possible). Stored 1300 number is the after-hours emergency line; no general office line published. ACTION: ask for maintenance-coordination supplier list."},
    {"business_name": "Smarter Communities", "segment": "strata", "suburb": "Sydney CBD", "service_area": "Sydney", "website": "https://smartercommunities.com.au", "contact_channel": "1800 519 642 (group sales) | (02) 9266 2600 (general)", "evidence_url": "https://smartercommunities.com.au", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.95, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Approach head office re group/STM-brand contractor arrangements",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct or Vendor Panel. PRIORITY: P1. VERIFIED 2026-09-05: 4,500 communities, 250+ staff, 11 offices ('$30B+' claim NOT on site — unverified). NSW brand = STM. 1800 519 642 is group-shared sales line (same as STM lead). ACTION: pitch group-level contractor arrangement; do not double-count sibling brands."},
    {"business_name": "BCS Strata Sydney (PICA Group)", "segment": "strata", "suburb": "Sydney CBD", "service_area": "Sydney", "website": "https://picagroup.com.au/branches/bcs-sydney/", "contact_channel": "1300 889 227 | bcs_sydney@bcssm.com.au", "evidence_url": "https://picagroup.com.au/branches/bcs-sydney/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.95, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Call branch, ask PICA FM contractor-onboarding route",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct or Vendor Panel. PRIORITY: P1. VERIFIED 2026-09-05: BCS confirmed in PICA Group entities (group claims 185k+ owners); procurement likely centralised. Strata Choice NOT in PICA entity list (no link). ACTION: call branch, ask for group contractor onboarding route."},
    {"business_name": "Progressive Strata Services", "segment": "strata", "suburb": "Edgecliff", "service_area": "Eastern Suburbs, CBD, Inner West", "website": "https://www.prostrata.com.au/", "contact_channel": "(02) 9389 9599", "evidence_url": "https://www.prostrata.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.6, "G": 1.0, "M": 0.85, "E": 0.8, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Direct approach to Edgecliff office re repaint cycles",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: boutique real, phone on site. Site self-contradicts (31 vs 23 yrs; Bondi vs Edgecliff). No portfolio figures. ACTION: direct pitch re eastern-suburbs repaint cycles."},
    {"business_name": "Sydney Strata Specialists", "segment": "strata", "suburb": "Bondi Beach", "service_area": "Sydney", "website": "https://sydneystrataspecialists.com.au/", "contact_channel": "02 8005 3850 | info@sydstrata.com.au", "evidence_url": "https://sydneystrataspecialists.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.55, "G": 1.0, "M": 0.85, "E": 0.8, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Direct pitch to Bondi office for eastern-suburbs repaints",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: small firm real ('50 years combined experience' only; counters render 0). Phone on site. ACTION: direct pitch for eastern-suburbs repaints."},
    {"business_name": "Strata United", "segment": "strata", "suburb": "Ultimo", "service_area": "Sydney", "website": "https://www.strataunited.com.au/", "contact_channel": "1300 445 900 | info@strataunited.com.au", "evidence_url": "https://www.strataunited.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.6, "G": 1.0, "M": 0.85, "E": 0.85, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Pitch repairs-maintenance team re contractor panel",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: boutique, 5 Sydney branches, site explicitly covers contractor scheduling/verification of works. Phone on site. ACTION: pitch repairs & maintenance team re contractor panel."},
    {"business_name": "Strata Sense", "segment": "strata", "suburb": "Sydney", "service_area": "Sydney, Newcastle", "website": "https://www.stratasense.com.au/", "contact_channel": "1300 859 044", "evidence_url": "https://stratasense.com.au/contact/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.55, "G": 1.0, "M": 0.85, "E": 0.7, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Phone approach, Surry Hills office",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: real, small (Surry Hills + Newcastle). Site blocks automated fetch (403) — phone verified via search only. ACTION: phone approach, ask for contractor process."},
    {"business_name": "Absolute Strata", "segment": "strata", "suburb": "Sydney", "service_area": "Sydney Metro, Regional NSW", "website": "https://absolutestrata.com.au/", "contact_channel": "02 9553 0244 | 1300 012 800 | info@absolutestrata.com.au", "evidence_url": "https://absolutestrata.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.6, "G": 0.9, "M": 0.85, "E": 0.8, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Pitch Kogarah head office re Sydney Metro repaint works",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: 20+ yrs confirmed; head office Kogarah (+ Dubbo/Orange — part-portfolio outside Sydney). Phones on site. ACTION: pitch Kogarah HQ re Sydney Metro repaints."},
    {"business_name": "Platinum Strata Management", "segment": "strata", "suburb": "Milsons Point", "service_area": "Central Coast, North Shore", "website": "https://platinumstratamanagement.com.au/", "contact_channel": "(02) 9922 4117", "evidence_url": "https://platinumstratamanagement.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.4, "G": 0.9, "M": 0.85, "E": 0.7, "R": 0.7, "risk": 0.1, "cost": 0.15},
     "next_action": "Direct pitch for North Shore buildings",
     "notes": "RELEVANCE: 7/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: real boutique; Milsons Point address is PO Box only; North Shore + Central Coast split; no size/tenure claims. Phone on site. ACTION: direct pitch for North Shore repaints."},
    {"business_name": "Whelan Property Group", "segment": "strata", "suburb": "Sydney", "service_area": "NSW", "website": "https://www.whelanproperty.com.au/", "contact_channel": "02 9219 4111", "evidence_url": "https://www.whelanproperty.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.9, "G": 1.0, "M": 0.95, "E": 0.9, "R": 0.9, "risk": 0.05, "cost": 0.1},
     "next_action": "Pitch Ultimo/Merrylands offices — 2hr work-order desk",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct. PRIORITY: P1. VERIFIED 2026-09-05: formed 2005 confirmed; residential/commercial/industrial + BMC; in-house maintenance desk commits to work orders within 2 hours (strong routine-commissioning signal). Phone on site. ACTION: pitch both offices; lead with speed-to-quote."},
    {"business_name": "Strata Real Estate Services", "segment": "strata", "suburb": "Sydney", "service_area": "Northern Beaches, North Shore, South, East, West Sydney", "website": "https://stratares.com.au/", "contact_channel": "1300 997 905", "evidence_url": "https://stratares.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.6, "G": 0.9, "M": 0.85, "E": 0.8, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Direct pitch; ask maintenance/repairs coordination process",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: since 1957 family claim; Sydney-wide but region extends to Tweed Heads/Kosciuszko; no street address published. Website .com 301s to .com.au (corrected). Phone on site. ACTION: direct pitch, ask repairs coordination process."},
    {"business_name": "Civium Strata NSW", "segment": "strata", "suburb": "North Strathfield", "service_area": "Sydney, National", "website": "https://civium.com.au/nsw/", "contact_channel": "(02) 9715 3999 | enquiries@civium.com.au", "evidence_url": "https://civium.com.au/contact-us/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.65, "G": 1.0, "M": 0.9, "E": 0.85, "R": 0.8, "risk": 0.1, "cost": 0.15},
     "next_action": "Pitch NSW office — they source and manage trades directly",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: site states 'we coordinate all necessary trades and service providers' + verifies contractor insurance; specialises small-to-medium schemes; 1/13 George St North Strathfield. Phone verified on contact page. ACTION: pitch NSW office directly."},
    {"business_name": "Strata Choice", "segment": "strata", "suburb": "Sydney CBD", "service_area": "Sydney", "website": "https://www.stratachoice.com.au/", "contact_channel": "1300 322 213 | (02) 9249 9800 | info@stratachoice.com.au", "evidence_url": "https://www.stratachoice.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.95, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Approach re vendor panel for CBD high-rise repaints",
     "notes": "RELEVANCE: 10/10. APPROACH: Direct or Vendor Panel. PRIORITY: P1. VERIFIED 2026-09-05: since 1984, 30,000+ owners, marquee sites (25 Martin Place, Greenland Centre). Independent family-owned — NO PICA link (absent from PICA entities). Published address is GPO Box. ACTION: approach re vendor panel for CBD high-rise repaints."},
    {"business_name": "Proactive Strata Services", "segment": "strata", "suburb": "West Ryde", "service_area": "Sydney", "website": "", "contact_channel": "02 9807 9255", "evidence_url": "https://stratamanagers.net.au/company.aspx?id=204&Council=Canada+Bay&businessname=Proactive+Strata+Services", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.45, "G": 1.0, "M": 0.85, "E": 0.6, "R": 0.7, "risk": 0.1, "cost": 0.15},
     "next_action": "Call 02 9807 9255; pitch strata repaint capability",
     "notes": "RELEVANCE: 7/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: real boutique, directory-only footprint (no own website). Phone consistent across directories. ACTION: call, pitch repaint capability directly to managers."},
    {"business_name": "Guardian Strata", "segment": "strata", "suburb": "Leichhardt", "service_area": "Sydney", "website": "https://www.guardianstrata.com.au", "contact_channel": "02 8030 8950 | admin@guardianstrata.com.au", "evidence_url": "https://www.stratamanagement.com/australia/leichhardt/strata-title-management/guardian-strata", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.5, "G": 1.0, "M": 0.85, "E": 0.5, "R": 0.7, "risk": 0.25, "cost": 0.15},
     "next_action": "Call first to CONFIRM still trading (website dead)",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: RISK — stored domain guardianstrata.com.au fails DNS (alt domain also dead); number still live on directories updated Aug 2026. Trading status unverified. ACTION: call first to confirm trading before investing effort."},
    {"business_name": "Ace Body Corporate Management", "segment": "strata", "suburb": "Balmain", "service_area": "Sydney", "website": "https://www.acebodycorp.com.au/balmain/", "contact_channel": "02 9818 6842 (official) | 0400 549 724 (directory, unverified)", "evidence_url": "https://www.acebodycorp.com.au/balmain/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.4, "G": 1.0, "M": 0.85, "E": 0.85, "R": 0.7, "risk": 0.1, "cost": 0.15},
     "next_action": "Call 02 9818 6842 (official Balmain branch line)",
     "notes": "RELEVANCE: 7/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: Balmain franchise confirmed on acebodycorp.com.au (franchisee owner-operated = single decision unit). CORRECTED phone: official branch line 02 9818 6842 replaces directory mobile. ACTION: call official line, ask for the franchisee principal."},
    {"business_name": "Strata Excellence", "segment": "strata", "suburb": "Sydney CBD", "service_area": "Eastern Suburbs, North Shore, Northern Beaches, Inner West, Western, Blue Mountains", "website": "https://www.strataexcellence.com.au/", "contact_channel": "1300 16 16 37", "evidence_url": "https://www.strataexcellence.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.6, "G": 1.0, "M": 0.85, "E": 0.85, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Pitch repaints for City Fringe / Inner West / East schemes",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: JPRW Property Pty Ltd ABN 59 614 981 207, L21 133 Castlereagh St; boutique by design ('small portfolio per manager'). Phone on site. ACTION: pitch its metro schemes."},
    {"business_name": "Foreshew Strata Agency", "segment": "strata", "suburb": "Menai", "service_area": "Sydney Metro, South Coast, Illawarra", "website": "https://www.foreshewstrata.com.au/", "contact_channel": "02 8379 6631 (official) | 1300 774 784 (not on site)", "evidence_url": "https://www.foreshewstrata.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.45, "G": 0.9, "M": 0.85, "E": 0.8, "R": 0.7, "risk": 0.15, "cost": 0.15},
     "next_action": "Call 02 8379 6631 re Repairs & Maintenance channel",
     "notes": "RELEVANCE: 7/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: strata manager with repairs/maintenance service confirmed. CORRECTED phone: 02 8379 6631 (official site; stored 1300 not displayed). Menai suburb not verifiable (no address on site; after-hours number has Illawarra prefix). ACTION: call official line, offer repaints via R&M channel."},
    {"business_name": "Elevated Strata Communities", "segment": "strata", "suburb": "Alexandria", "service_area": "All Sydney", "website": "https://elevatedstrata.com.au/", "contact_channel": "1300 951 203 | hello@elevatedsm.com.au", "evidence_url": "https://elevatedsm.com.au/contact-us/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.5, "G": 1.0, "M": 0.85, "E": 0.8, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Call 1300 951 203; pitch mixed-use and BMC repaints",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: founded 2020 confirmed, A1/35-39 Bourke Rd Alexandria; portfolio size unpublished. Phone on site. ACTION: call, pitch mixed-use/BMC repaints."},
    {"business_name": "Strata Title Management (STM)", "segment": "strata", "suburb": "Sydney", "service_area": "NSW", "website": "https://www.stratatitle.com.au/", "contact_channel": "(02) 9266 2600 | 1800 519 642 | info@stratatitle.com.au", "evidence_url": "https://www.stratatitle.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.85, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Pitch STM managers; ask if Smarter Communities runs group trades panel",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct or Vendor Panel. PRIORITY: P1. VERIFIED 2026-09-05: since 1978; 27,000 lots / 1,500 buildings; Smarter Communities parent CONFIRMED on own site. 1800 519 642 = group-shared quote line. Same group as Smarter Communities lead — pitch group-level, do not double-count sibling brands. ACTION: ask about group trades panel."},
    {"business_name": "Michael Roberts Strata Management", "segment": "strata", "suburb": "Sydney", "service_area": "St George, Sutherland Shire, Eastern Suburbs", "website": "https://www.mrstrata.com.au/", "contact_channel": "(02) 8567 5900", "evidence_url": "https://www.mrstrata.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.55, "G": 1.0, "M": 0.85, "E": 0.8, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Call (02) 8567 5900 re St George/Sutherland repaints",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: Hurstville (Suite 7, 11 Forest Rd), 40+ yrs, family-owned, residential/commercial/industrial. Phone on site. ACTION: call, pitch southern-suburbs repaint programs."},
    {"business_name": "Delux Building Management Group", "segment": "strata", "suburb": "Gladesville", "service_area": "Sydney", "website": "https://deluxgroup.com.au", "contact_channel": "1300 606 666 | info@deluxgroup.com.au", "evidence_url": "https://deluxgroup.com.au", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.7, "G": 1.0, "M": 0.8, "E": 0.85, "R": 0.85, "risk": 0.1, "cost": 0.15},
     "next_action": "Apply as vetted painting subcontractor under Delux FM contracts",
     "notes": "RELEVANCE: 8/10. APPROACH: Subcontractor Pathway. PRIORITY: P2. VERIFIED 2026-09-05: real (est 2017, Suite 3 L4 436-484 Victoria Rd Gladesville); body corporate + FM; self-performs some services, trades engaged as 'vetted contractors'. Phone confirmed on official site. ACTION: apply as vetted painting subcontractor."},
    {"business_name": "IB Property", "segment": "strata", "suburb": "Annandale", "service_area": "Sydney", "website": "https://ibproperty.com.au", "contact_channel": "(02) 9221 3333 | info@ibproperty.com.au", "evidence_url": "https://ibproperty.com.au/contact/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.8, "G": 1.0, "M": 0.9, "E": 0.85, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "One group pitch covering IB Property + Montano + Complete Strata",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct. PRIORITY: P1. VERIFIED 2026-09-05: IB Group confirmed (ibgroup.au — strata/FM/insurance/maintenance ecosystem); offices Annandale/Parramatta/St Leonards. Stored 'Head of FM' name NOT verified (removed). GROUP DUPE: one group pitch also covers Montano Strata + Complete Strata Management brands. ACTION: call, pitch group-wide FM painting program."},
    {"business_name": "Excel Building Management", "segment": "strata", "suburb": "Sydney", "service_area": "Sydney", "website": "https://excelbm.com.au", "contact_channel": "(02) 9518 8577 | after-hours 1300 985 000", "evidence_url": "https://excelbm.com.au/contact-us/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.8, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Call (02) 9518 8577; pitch premium building repaints",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct. PRIORITY: P1. VERIFIED 2026-09-05: identity found — 'Excel BM', 302/55 Miller St Pyrmont, since 2001; 50+ schemes / $10B+ property (Skye by Crown, Archibald Residences, World Tower, 74 Pitt St); 300+ maintenance requests/month claimed. PHONE FOUND: (02) 9518 8577. Not related to 'Excel Building Services'. ACTION: call, pitch premium repaints."},
    {"business_name": "National Facilities Management", "segment": "strata", "suburb": "Sydney", "service_area": "Sydney", "website": "https://nationalfm.com.au", "contact_channel": "1300 820 330 | mail@nationalfm.com.au", "evidence_url": "https://nationalfm.com.au", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.8, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Call 1300 820 330; pitch painting under strata/high-rise FM contracts",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct. PRIORITY: P1. VERIFIED 2026-09-05: National Facilities Management Pty Ltd, ABN 65 159 752 324 (active since 2012), 56 Dickson Ave Artarmon. Family-owned confirmed; '40+ years' on site vs '35yr' in old note (contradiction recorded). Premium portfolio claimed (One Sydney Harbour, Barangaroo). PHONE FOUND: 1300 820 330. ACTION: call, pitch FM painting."},
    {"business_name": "Bond Services", "segment": "strata", "suburb": "Meadowbank", "service_area": "Sydney, Northern Beaches, Parramatta", "website": "https://bondservices.com.au", "contact_channel": "(02) 8117 8184 | social@bondservices.com.au", "evidence_url": "https://bondservices.com.au/pages/about", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.3, "G": 1.0, "M": 0.1, "E": 0.85, "R": 0.3, "risk": 0.2, "cost": 0.2},
     "next_action": "Ask for strata-client manager introductions (referral path)",
     "notes": "RELEVANCE: 5/10. APPROACH: Partnership/Referral. PRIORITY: P3. VERIFIED 2026-09-05: CONFIRMED cleaning-only (family-owned since 1988, strata cleaning Sydney-wide) — NOT a painting customer. Real offices Mona Vale + Parramatta (Meadowbank is PO Box). Value = introductions to their strata clients. ACTION: ask for client-manager introductions."},
    # ══ COMMERCIAL ══
    {"business_name": "ESR Group", "segment": "commercial", "suburb": "Sydney CBD", "service_area": "NSW, SA", "website": "https://au.esr.com", "contact_channel": "Main: +61 2 9186 4700 | Fergus Adamson (GM Property Services NSW) +61 415 784 898 | Nicole Stephens +61 429 479 141", "evidence_url": "https://au.esr.com/contact/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.85, "G": 0.8, "M": 0.75, "E": 0.85, "R": 0.8, "risk": 0.1, "cost": 0.15},
     "next_action": "Call property services re NSW warehouse/logistics repaint panel",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct or Vendor Panel. PRIORITY: P2. VERIFIED 2026-09-05: A$22.9B AUM confirmed; '195 assets' count not on site (unverified). Main line verified on contact page; named property-services contacts from earlier collection retained. ACTION: pitch NSW industrial/logistics repaint panel."},
    {"business_name": "Siemens Australia - Smart Infrastructure", "segment": "commercial", "suburb": "North Ryde", "service_area": "NSW", "website": "https://siemens.com", "contact_channel": "Buildings Service NSW: 1300 782 379 | General: 137 222", "evidence_url": "https://www.siemens.com/en-us/company/about/contact-australia/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.1, "G": 1.0, "M": 0.05, "E": 0.8, "R": 0.05, "risk": 0.2, "cost": 0.3},
     "next_action": "Archive unless Siemens is head contractor on a specific NSW project",
     "notes": "RELEVANCE: 3/10 (was 7 — DOWNGRADED). APPROACH: Intel-Only. PRIORITY: P3. VERIFIED 2026-09-05: North Ryde office real, but Siemens buys BMS/HVAC/fire TECH, not painting; own property portfolio small; painting would sit under a builder/facade contractor. Not a painting customer. ACTION: archive unless named head contractor on a project."},
    {"business_name": "SGCH", "segment": "commercial", "suburb": "Liverpool", "service_area": "Sydney, Melbourne, Brisbane", "website": "https://sgch.com.au", "contact_channel": "1800 573 370 | office@sgch.com.au", "evidence_url": "https://sgch.com.au", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.85, "G": 1.0, "M": 0.8, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Ask maintenance team re vacant-property/turn repaint suppliers",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct or Vendor Panel. PRIORITY: P2. VERIFIED 2026-09-05: 7,082 homes confirmed, Tier-1 community housing provider, Liverpool NSW. Phone on site. ACTION: ask maintenance team about turnover repaint program suppliers."},
    {"business_name": "Dexus", "segment": "commercial", "suburb": "Sydney CBD", "service_area": "NSW", "website": "https://dexus.com", "contact_channel": "+61 2 9017 1100", "evidence_url": "https://www.dexus.com/get-in-touch.html", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.9, "G": 1.0, "M": 0.7, "E": 0.9, "R": 0.75, "risk": 0.15, "cost": 0.2},
     "next_action": "Register on Dexus supplier portal; request NSW repaint scope",
     "notes": "RELEVANCE: 8/10. APPROACH: Panel/Tender. PRIORITY: P2. VERIFIED 2026-09-05: Sydney HQ Quay Quarter Tower confirmed. Entry = supplier portal, not cold call. Phone verified. ACTION: register on supplier portal, request NSW facilities repaint scope."},
    {"business_name": "Woolworths Group", "segment": "commercial", "suburb": "Bella Vista", "service_area": "National (NSW focus)", "website": "https://woolworthsgroup.com.au", "contact_channel": "+61 2 8885 0000", "evidence_url": "https://woolworthsgroup.com.au/au/en/contact-us.html", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.85, "G": 1.0, "M": 0.6, "E": 0.7, "R": 0.7, "risk": 0.2, "cost": 0.2},
     "next_action": "Contact property procurement re store refresh program supplier entry",
     "notes": "RELEVANCE: 7/10. APPROACH: Panel/Tender. PRIORITY: P2. VERIFIED 2026-09-05: phone verified. CLAIM CORRECTED: Westfield centres belong to Scentre Group, NOT Woolworths — demand = supermarket store maintenance/refresh programs via property procurement. ACTION: contact property procurement re supplier entry."},
    {"business_name": "Cushman and Wakefield Sydney", "segment": "commercial", "suburb": "Sydney CBD", "service_area": "ANZ", "website": "https://cushmanwakefield.com", "contact_channel": "+61 2 8243 9999", "evidence_url": "https://www.cushmanwakefield.com/en/australia/offices/sydney", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.9, "G": 1.0, "M": 0.8, "E": 0.9, "R": 0.8, "risk": 0.05, "cost": 0.1},
     "next_action": "Ask NSW FM team re trades subcontractor panel",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct or Vendor Panel. PRIORITY: P2. VERIFIED 2026-09-05: Sydney office L22 1 O'Connell St confirmed; IFM & Asset Services outsources trades — we are that trade. Phone matches official office page. ACTION: ask NSW FM team re subcontractor panel."},
    {"business_name": "Nation", "segment": "commercial", "suburb": "Merrylands", "service_area": "Sydney", "website": "https://nation.com.au", "contact_channel": "02 9090 4606", "evidence_url": "https://nation.com.au", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.6, "G": 1.0, "M": 0.85, "E": 0.7, "R": 0.8, "risk": 0.15, "cost": 0.15},
     "next_action": "Call operations re make-good / unit-turn / common-area repaints",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: identity resolved = build-to-rent platform of Coronation Property ('Made with Coronation'). 7 Sydney buildings confirmed (2 operating: Merrylands + Parramatta; 5 pipeline); '~3,500 apartments' is press-reported pipeline, not official — unverified. PHONE FOUND: 02 9090 4606. ACTION: call operations re unit-turn repaints."},
    {"business_name": "Opera Australia", "segment": "commercial", "suburb": "Surry Hills", "service_area": "Sydney, Melbourne", "website": "https://opera.org.au", "contact_channel": "(02) 9699 1099 (The Opera Centre)", "evidence_url": "https://opera.org.au/contact-us/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.3, "G": 1.0, "M": 0.6, "E": 0.85, "R": 0.4, "risk": 0.1, "cost": 0.2},
     "next_action": "Contact facilities re periodic venue repaint schedule",
     "notes": "RELEVANCE: 6/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: real multi-site venue owner (Opera Centre Surry Hills + Sydney Opera House tenancy + Melbourne) but small, episodic painting volume. PHONE FOUND: (02) 9699 1099. ACTION: contact facilities re periodic repaint schedule."},
    {"business_name": "Savills Australia", "segment": "commercial", "suburb": "Sydney CBD", "service_area": "National", "website": "https://savills.com.au", "contact_channel": "+61 2 8215 8888 (L25, 1 Farrer Place)", "evidence_url": "https://www.savills.com.au/offices/sydney.aspx", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.9, "G": 1.0, "M": 0.85, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Register as painting contractor with NSW property management team",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct or Vendor Panel. PRIORITY: P1. VERIFIED 2026-09-05: global property manager, contractor tendering + CapEx/OpEx cycles. PHONE FOUND: +61 2 8215 8888, L25 1 Farrer Place (official office page). ACTION: register as painting contractor with NSW property management."},
    {"business_name": "CBRE Advisory Charter Hall", "segment": "commercial", "suburb": "Sydney CBD", "service_area": "Sydney CBD", "website": "https://www.cbre.com.au", "contact_channel": "+61 2 9333 3333 (L21, 363 George St — confirm on call)", "evidence_url": "https://www.cbre.com.au/press-releases/facilities-management-award-recognises-strength-of-enduring-client-partnership", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.9, "G": 1.0, "M": 0.85, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "Request CBRE FM supplier prequalification for Charter Hall scope",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct or Vendor Panel. PRIORITY: P1. VERIFIED 2026-09-05: CBRE-Charter Hall FM relationship CONFIRMED (153 office/industrial assets, ~800k sqm office + 2.5M sqm industrial — CBRE press release + trade press). PHONE FOUND: +61 2 9333 3333 via search snippet (site blocked fetch — confirm on call). ACTION: request FM supplier prequalification."},
    {"business_name": "News Corp Australia", "segment": "commercial", "suburb": "Surry Hills", "service_area": "National (Sydney HQ)", "website": "https://www.newscorpaustralia.com", "contact_channel": "(02) 9288 3000", "evidence_url": "https://www.newscorpaustralia.com/contact-us/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.4, "G": 1.0, "M": 0.6, "E": 0.85, "R": 0.5, "risk": 0.1, "cost": 0.2},
     "next_action": "Call switchboard, ask for facilities manager (Holt St works)",
     "notes": "RELEVANCE: 7/10 (was 9 — trimmed). APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: one corporate HQ + bureaus, not a large managed portfolio. PHONE FOUND: (02) 9288 3000 ('Call us on', official site). Website corrected: official domain is newscorpaustralia.com (stored newscorp.com.au has TLS fault). ACTION: call switchboard, ask for facilities manager."},
    {"business_name": "Mission Australia", "segment": "commercial", "suburb": "Sydney", "service_area": "National", "website": "https://missionaustralia.com.au", "contact_channel": "1800 951 123 (L7, 580 George St)", "evidence_url": "https://www.missionaustralia.com.au/contact-us/services-and-offices/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.8, "G": 0.8, "M": 0.8, "E": 0.9, "R": 0.85, "risk": 0.1, "cost": 0.15},
     "next_action": "Contact national property team re NSW housing repaints",
     "notes": "RELEVANCE: 8/10. APPROACH: Direct or Vendor Panel. PRIORITY: P2. VERIFIED 2026-09-05: national housing portfolio (strata, facilities, defects, capital works). PHONE FOUND: 1800 951 123, L7 580 George St (official services-and-offices page). ACTION: contact property/facilities team re NSW housing repaints."},
    {"business_name": "Capstone Recruitment (Head of Technical Property - undisclosed client)", "segment": "commercial", "suburb": "Sydney", "service_area": "National", "website": "https://www.capstonerecruitment.com.au/", "contact_channel": "Phil O Keeffe 0404 041 904 (recruiter)", "evidence_url": "https://www.capstonerecruitment.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.1, "G": 0.8, "M": 0.1, "E": 0.7, "R": 0.1, "risk": 0.35, "cost": 0.2},
     "next_action": "Call recruiter to profile the undisclosed national client",
     "notes": "RELEVANCE: 5/10 (was 10 — reclassified). APPROACH: Intel-Only. PRIORITY: P3. VERIFIED 2026-09-05: Capstone = real Sydney property/infrastructure recruiter — NOT a painting customer. The $285K Head of Technical Property role belongs to an UNDISCLOSED national client; recruiters often protect client identity. One call may identify a major account. ACTION: call recruiter, profile the client."},
    # ══ GOVERNMENT ══
    {"business_name": "NSW Department of Planning Housing and Infrastructure", "segment": "government", "suburb": "Parramatta", "service_area": "NSW", "website": "https://www.planning.nsw.gov.au", "contact_channel": "1300 305 695 (Planning Portal enquiries)", "evidence_url": "https://www.planning.nsw.gov.au/about-us/contact-us", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.7, "G": 1.0, "M": 0.5, "E": 0.6, "R": 0.6, "risk": 0.25, "cost": 0.3},
     "next_action": "Register on buy.nsw Supplier Hub; monitor DPHI property tenders",
     "notes": "RELEVANCE: 7/10. APPROACH: Panel/Tender. PRIORITY: P2. VERIFIED 2026-09-05: 4 Parramatta Square confirmed; official NSW directory lists NO general switchboard. PHONE FOUND: 1300 305 695 (Planning Portal enquiry line). dphi.nsw.gov.au auto-redirects; planning.nsw.gov.au is the working domain. ACTION: register on buy.nsw Supplier Hub, monitor property-maintenance tenders."},
    {"business_name": "Sydney Water", "segment": "government", "suburb": "Parramatta", "service_area": "Greater Sydney", "website": "https://www.sydneywater.com.au", "contact_channel": "Suppliers: 1300 690 399 (Business Connect) | Customer: 13 20 92", "evidence_url": "https://www.sydneywater.com.au/about-us/our-suppliers/supplier-registration.html", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.7, "G": 1.0, "M": 0.5, "E": 0.9, "R": 0.6, "risk": 0.2, "cost": 0.3},
     "next_action": "Submit supplier self-registration; complete SAP Ariba questionnaire",
     "notes": "RELEVANCE: 7/10. APPROACH: Panel/Tender. PRIORITY: P2. VERIFIED 2026-09-05: supplier path found — Business Connect 1300 690 399 + SAP Ariba registration (stored 13 20 92 is the CUSTOMER line, wrong class for vendors). Thousands of assets. ACTION: submit supplier self-registration form; complete Ariba questionnaire."},
    {"business_name": "City of Canterbury Bankstown", "segment": "government", "suburb": "Bankstown", "service_area": "Canterbury-Bankstown LGA", "website": "https://www.cbcity.nsw.gov.au", "contact_channel": "02 9707 9000 | council@cbcity.nsw.gov.au", "evidence_url": "https://www.cbcity.nsw.gov.au/your-council/contact-us", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.6, "G": 1.0, "M": 0.55, "E": 0.85, "R": 0.6, "risk": 0.2, "cost": 0.25},
     "next_action": "Contact procurement re building-maintenance/painting panel EOI",
     "notes": "RELEVANCE: 7/10. APPROACH: Panel/Tender. PRIORITY: P2. VERIFIED 2026-09-05: Tier-1 metro LGA; phone confirmed in site footer. ACTION: contact procurement re building-maintenance panel EOI."},
    {"business_name": "Sydney Olympic Park Authority", "segment": "government", "suburb": "Sydney Olympic Park", "service_area": "Sydney", "website": "https://www.sydneyolympicpark.nsw.gov.au", "contact_channel": "(02) 9714 7888", "evidence_url": "https://www.sydneyolympicpark.com.au/contact-us", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.5, "G": 1.0, "M": 0.3, "E": 0.8, "R": 0.3, "risk": 0.2, "cost": 0.2},
     "next_action": "Diary SR01200 award; approach winning FM for painting subcontract",
     "notes": "RELEVANCE: 6/10. APPROACH: Watch. PRIORITY: P2. VERIFIED 2026-09-05: NOT a direct painting lead. RFT SR01200 Property Management Services ($500K-$3.5M) closes 7-Sep-2026 3pm (TenderHub listing as of 1-Sep; buy.nsw URL blocks automated fetch — status unverified there). PHONE FOUND: (02) 9714 7888. ACTION: diary the award; approach winning FM re painting subcontract."},
    {"business_name": "City of Parramatta", "segment": "government", "suburb": "Parramatta", "service_area": "Parramatta LGA", "website": "https://www.cityofparramatta.nsw.gov.au", "contact_channel": "1300 617 058", "evidence_url": "https://www.cityofparramatta.nsw.gov.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.65, "G": 1.0, "M": 0.6, "E": 0.8, "R": 0.65, "risk": 0.2, "cost": 0.25},
     "next_action": "Subscribe to tender alerts; request building-services panel details",
     "notes": "RELEVANCE: 8/10 (was 8.5 — integer scale). APPROACH: Panel/Tender. PRIORITY: P2. VERIFIED 2026-09-05: Tier-1 LGA, coordinates building services/contractors. PHONE FOUND: 1300 617 058 (official site). ACTION: subscribe to tender alerts; ask for building-services panel details."},
    # ══ SUBCONTRACTOR / REFERRAL / INTEL ══
    {"business_name": "BPS Strata and Insurance Restoration", "segment": "subcontractor", "suburb": "Kingsgrove", "service_area": "ACT, NSW", "website": "https://www.bpsstrata.com.au/", "contact_channel": "1300 724 814", "evidence_url": "https://www.bpsstrata.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.1, "G": 1.0, "M": 0.0, "E": 0.8, "R": 0.05, "risk": 0.5, "cost": 0.2},
     "next_action": "None — log as competitor; overflow-subcontract peer only",
     "notes": "RELEVANCE: 2/10 (was 7 — COMPETITOR). APPROACH: Intel-Only. PRIORITY: P3. VERIFIED 2026-09-05: NOT-A-CUSTOMER — trade firm with directly employed licensed tradesmen, strata & insurance restoration since 1978 NSW/ACT (site live at bpsstrata.com.au; 73 Kingsway Kingsgrove). Buys no painting, sells it. ACTION: none; keep as overflow-subcontract peer only."},
    {"business_name": "Downer Group", "segment": "subcontractor", "suburb": "North Ryde", "service_area": "National (NSW/ACT + QLD)", "website": "https://downergroup.com", "contact_channel": "1800 369 637 (official) | +61 2 9468 9700", "evidence_url": "https://downergroup.com/supply-to-downer/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.95, "G": 0.9, "M": 0.8, "E": 0.95, "R": 0.9, "risk": 0.1, "cost": 0.2},
     "next_action": "Complete Vendor Assessment Portal risk assessment",
     "notes": "RELEVANCE: 9/10. APPROACH: Subcontractor Pathway. PRIORITY: P1. VERIFIED 2026-09-05: Defence PAS claim REAL — $3.05B East Coast PAS (NSW/ACT/QLD) commencing Feb 2026 (Downer news). Supply path verified: downergroup.com/supply-to-downer (risk assessment → supplier minimum requirements → terms). '300+ sites' unverified; Spotless ownership corroborated. PHONE FOUND: 1800 369 637 (official contact page; stored line no longer displayed). ACTION: complete Vendor Assessment Portal; target PAS estate-maintenance subcontracting."},
    {"business_name": "TalentWeb Property (Donny Mudiasa)", "segment": "subcontractor", "suburb": "Sydney", "service_area": "Sydney", "website": "https://www.talentweb.com.au", "contact_channel": "Donny Mudiasa 0430 010 756 | dmudiasa@talentweb.com.au (unverified)", "evidence_url": "https://www.talentweb.com.au/sectors/facilities-property-management-recruitment/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.1, "G": 1.0, "M": 0.1, "E": 0.6, "R": 0.1, "risk": 0.3, "cost": 0.2},
     "next_action": "Follow their FM job alerts as early-warning for FM contract churn",
     "notes": "RELEVANCE: 4/10 (was 7). APPROACH: Intel-Only. PRIORITY: P3. VERIFIED 2026-09-05: real Sydney FM/property recruiter (B Corp, 654 SEEK reviews). Stored contact name/number NOT directly verified (site refused automated fetch). Value = early warning on FM moves, not a customer. ACTION: follow FM job alerts."},
    {"business_name": "Complete Staff Solutions", "segment": "subcontractor", "suburb": "Sydney", "service_area": "National", "website": "https://www.completestaff.com.au", "contact_channel": "1800 308 308 | online@completestaff.com.au", "evidence_url": "https://www.completestaff.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.15, "G": 1.0, "M": 0.1, "E": 0.8, "R": 0.1, "risk": 0.3, "cost": 0.2},
     "next_action": "Monitor Government Sector placements for council contract signals",
     "notes": "RELEVANCE: 5/10 (was 8 — trimmed). APPROACH: Intel-Only. PRIORITY: P3. VERIFIED 2026-09-05: labour-hire firm serving Government confirmed; 'Local Govt property roles' is NOT a named specialty on site. Phone on site. Indirect intel only. ACTION: monitor government placements for council signals."},
    {"business_name": "Core Talent (Premium strata ~90 lots - undisclosed)", "segment": "strata", "suburb": "Sydney", "service_area": "Sydney", "website": "https://www.coretalent.com.au/", "contact_channel": "Olivia 0406 560 343 (recruiter)", "evidence_url": "https://www.coretalent.com.au/jobs/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.1, "G": 1.0, "M": 0.2, "E": 0.9, "R": 0.15, "risk": 0.25, "cost": 0.1},
     "next_action": "Call Olivia, identify the building, pitch its strata manager directly",
     "notes": "RELEVANCE: 9/10 (intel value). APPROACH: Intel-Only. PRIORITY: P1. VERIFIED 2026-09-05: intel CONFIRMED CURRENT on recruiter's own jobs page: 'Building Manager, Sydney NSW, $115K, 90 lots - Single strata plan, Eastern Suburbs'; LinkedIn ad notes the Building Manager liaises with the Strata Manager = the building HAS a strata manager (that firm is the door). NOT a customer itself — highest-leverage intel call in the list. Recruiter site blocks fetch; stored number not re-verified. ACTION: call Olivia, identify building, pitch its strata manager."},
    # ══ OTHER ══
    {"business_name": "Strata Republic", "segment": "strata", "suburb": "Sydney CBD", "service_area": "All Sydney + Byron Bay", "website": "https://www.stratarepublic.com.au/", "contact_channel": "1300 884 104", "evidence_url": "https://www.stratarepublic.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.7, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.8, "risk": 0.05, "cost": 0.1},
     "next_action": "Call 1300 884 104; pitch strata repaint program",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct. PRIORITY: P1. VERIFIED 2026-09-05: real; 8 Harvey St Pyrmont; ABN 15 110 469 620 + licence 1305102 match stored values. Founder sits on SCA NSW board (warm-door potential). PHONE FOUND: 1300 884 104 (official site). ACTION: call, pitch repaint program across all-Sydney portfolio."},
    {"business_name": "Neighbourly Strata (VJ Ray)", "segment": "strata", "suburb": "Sydney", "service_area": "Sydney South West + metro", "website": "https://www.neighbourly.co", "contact_channel": "02 8880 1040", "evidence_url": "https://www.neighbourly.co/contact", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.6, "G": 1.0, "M": 0.85, "E": 0.85, "R": 0.75, "risk": 0.1, "cost": 0.15},
     "next_action": "Pitch as Neighbourly Strata; drop the old VJ Ray name",
     "notes": "RELEVANCE: 7/10. APPROACH: Direct. PRIORITY: P2. VERIFIED 2026-09-05: REBRAND CONFIRMED — V J Ray Pty Ltd (ABN 16 000 397 973, est 1962) registered business name 'Neighbourly Strata'. Current offices: Sydney City / Miranda / Sydney Olympic Park / Norwest (stored Bankstown address superseded). PHONE FOUND: 02 8880 1040 (official contact page). ACTION: pitch under the Neighbourly name."},
    {"business_name": "CF Strata Management", "segment": "strata", "suburb": "Rosebery", "service_area": "Eastern Suburbs, Inner West, Southern Suburbs", "website": "https://cfstrata.com.au/", "contact_channel": "(02) 9313 6255", "evidence_url": "https://cfstrata.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.7, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.8, "risk": 0.05, "cost": 0.1},
     "next_action": "Call (02) 9313 6255; offer repaint tenders for premium schemes",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct. PRIORITY: P1. VERIFIED 2026-09-05: ABN 58 002 429 183; 40+ yrs; Rosebery; ~150 suburbs incl. Bondi/Vaucluse/Woollahra; SCA NSW corporate member; shares site with Wedd Realty. PHONE FOUND: (02) 9313 6255 (official site). ACTION: call, offer repaint tender quotes for premium eastern-suburbs schemes."},
    {"business_name": "Montano Strata", "segment": "strata", "suburb": "Annandale", "service_area": "Sydney", "website": "https://montanostrata.com.au/", "contact_channel": "(02) 9053 7637", "evidence_url": "https://montanostrata.com.au/", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.8, "G": 1.0, "M": 0.9, "E": 0.9, "R": 0.85, "risk": 0.05, "cost": 0.1},
     "next_action": "One pitch covering the whole IB Group portfolio",
     "notes": "RELEVANCE: 9/10. APPROACH: Direct. PRIORITY: P1. VERIFIED 2026-09-05: 2,500+ lots / 200+ schemes confirmed on site. GROUP DUPE CONFIRMED: ibgroup.au lists IB Property + Montano Strata + Complete Strata Management as one group; head office 75 Nelson St Annandale = same as IB Property lead. One group pitch covers three stored leads. PHONE FOUND: (02) 9053 7637. ACTION: call, pitch group-wide repaint program."},
    {"business_name": "Hays Property (Council client undisclosed)", "segment": "subcontractor", "suburb": "Sydney", "service_area": "Sydney", "website": "https://www.hays.com.au", "contact_channel": "02 8226 9600 (L14 Chifley Tower)", "evidence_url": "https://www.hays.com.au/jobs/property", "stage": "researched", "outreach_permission": "unknown",
     "score_inputs": {"P": 0.1, "G": 1.0, "M": 0.05, "E": 0.85, "R": 0.1, "risk": 0.25, "cost": 0.2},
     "next_action": "Mine job ad to identify which Council, then approach it directly",
     "notes": "RELEVANCE: 4/10 (was 7). APPROACH: Intel-Only. PRIORITY: P3. VERIFIED 2026-09-05: Hays = real property recruiter (never a painting buyer); placing Property Officer at an UNDISCLOSED Sydney Council ($50-60/hr, Seek 94361951). Sole value = the council signal (council hiring property staff implies future facility procurement). PHONE FOUND: 02 8226 9600 (official office locator). ACTION: identify the council from the ad, approach the council directly."},
]

def main():
    store = LeadStore(_db())
    now = datetime.now(timezone.utc).isoformat()
    ok = 0
    for rec in LEADS:
        r = store.create_account(TENANT, rec, now_iso=now)
        if r.get("ok"):
            ok += 1
            print(f"OK {rec['business_name']} | score={r.get('score'):.3f} | {r.get('recommendation')}")
        else:
            print(f"FAIL {rec['business_name']}: {r.get('error')}")
    print(f"\nDone: {ok}/{len(LEADS)} upserted with verified data")

if __name__ == "__main__":
    main()
