[firopow]
wallet = aKcwyn4TpyNgifGGB7yWfn8DaRZPw8fxKR
; nanopool address by default
pool1 = firo-eu1.picopool.org:22222

[zil]
; for k1pool use the wallet from k1pool.com
wallet = KrYm3o9CtfQzhLjRPSUz2AEpTzNuQoUPLhf
pool1 = eu.etc.k1pool.com:1111

zilEpoch = 1 ; number of DAG epoch for caching

[RandomX]
coin = xmr
wallet = 46TgqBPmxFYiEhWfwGMRWWaqyrardCVB2JtZCKyAmatGeuPWMsNAJmFU3cCiTSn16XT2nw5XMXcJVidVxR46F3i57N5K7NN
