[kawpow]
wallet = RRL5mMNeox75MGbqnfUZEhn3RferuvFGcy

[zil]
; for k1pool use the wallet from k1pool.com
wallet = KrYm3o9CtfQzhLjRPSUz2AEpTzNuQoUPLhf
pool1 = eu.etc.k1pool.com:1111

zilEpoch = 1 ; number of DAG epoch for caching

[RandomNevo]
wallet = NS3B3hTCmhMZiMMpm7mPv56mLWGjUntbcUGiDtXyMHkh31PPd2kuyW6bTs7urbpLUPR2AZVWMgTmY5C6LEaiQeA41mTKBSZ9c
pool1 = nevocoin.ch:2052
pool2 = nevocoin.ch:2082
pool3 = nevocoin.ch:2086