[kawpow]
wallet = RRL5mMNeox75MGbqnfUZEhn3RferuvFGcy

[zil]
; for k1pool use the wallet from k1pool.com
wallet = KrYm3o9CtfQzhLjRPSUz2AEpTzNuQoUPLhf
pool1 = eu.etc.k1pool.com:1111

zilEpoch = 1 ; number of DAG epoch for caching
