[kawpow]
wallet = RRL5mMNeox75MGbqnfUZEhn3RferuvFGcy

[zil]
; for f2pool use your username from f2pool.com
wallet = fenix31415
pool1 = etc-zil.f2pool.com:6200

zilEpoch = 1 ; number of DAG epoch for caching
